### ISSUE TITLE
Facing error in importing default_augraphy_pipeline

### ISSUE THREAD

**Issue by kwcckw** [sparkfish/augraphy#1]
Hi,

Looks like i'm facing error as below when running "from Augraphy import default_augraphy_pipeline":

      File "C:/augraphy/test1.py", line 12, in <module>
        from Augraphy import default_augraphy_pipeline
      
      ImportError: cannot import name 'default_augraphy_pipeline' from 'Augraphy'
      
probably can replace the following line in init file?

    __all__ = ["AugraphyPipeline","default_augraphy_pipeline"]

**Comment by tbrettallen** [comment]
I've made some corrections to the code that may affect this, but I am unable to reproduce this issue locally.

Can you confirm if this is still an issue or not please?

**Comment by kwcckw** [comment]
> 
> 
> I've made some corrections to the code that may affect this, but I am unable to reproduce this issue locally.
> 
> Can you confirm if this is still an issue or not please?

Yes, it's resolved now , thanks.
