### ISSUE TITLE
Markup class for strikethrough/underline

### ISSUE THREAD

**Issue by shaheryar1** [sparkfish/augraphy#100]
Should I create a `Markup`  ( as discussed in this [comment](https://github.com/sparkfish/augraphy/issues/63#issuecomment-919174591)) with the option to select between strikethrough, underline, or any other similar augmentation ?

**Comment by proofconstruction** [comment]
I think it's a great idea.

If we could control which text in the image receives the effect, even better

**Comment by proofconstruction** [comment]
Closed with merge of PR #101
