### ISSUE TITLE
Add Highlighter to Markup Augmentation

### ISSUE THREAD

**Issue by jboarman** [sparkfish/augraphy#103]
Using the same concept as the strikethrough markup style, a wide stroke thickness and color could be used to create a highlighter markup type (using alpha transparency in stroke color).

The alpha transparency value will require experimentation, but perhaps the alpha value might be randomized from 20% to 60%.  Apparently, OpenCV does not directly support alpha transparency colors at this point, so use of  `cv2.addWeighted()` must be used to apply this markup using transparency overlays (see [example gist](https://gist.github.com/IAmSuyogJadhav/305bfd9a0605a4c096383408bee7fd5c)).

Based on some trial and error, the following color ranges appear to align with popular highlighter color palettes:

```
orange: rgb => 255 .. 255, 160 .. 205,   0 ..   0
yellow: rgb => 200 .. 255, 255 .. 255,   0 ..   0
 green: rgb => 200 ..   0, 255 .. 255,   0 ..   0
  pink: rgb => 200 .. 255,   0 .. 125, 255 .. 255
  blue: rgb =>   0 ..  40, 120 .. 255, 255 .. 255
purple: rgb => 100 .. 180,   0 .. 140, 200 .. 255
```

![image](https://user-images.githubusercontent.com/1108065/135769597-9da4d575-2cd5-4cf1-8f6f-16e4df754d6c.png)

![image](https://user-images.githubusercontent.com/1108065/135769254-5334f41f-682f-4682-9d6b-2ef3ba418ea1.png)

**Comment by shaheryar1** [comment]
I am on it.

**Comment by shaheryar1** [comment]
I have added the highlight effect in the `Markup `class. Here are some results of the highlight effect.
For highlighter color palettes users can pass custom bgr colors via `markup_color` parameter.

![a](https://user-images.githubusercontent.com/43179913/135905974-2935f2ed-c6a9-49bd-8387-5e5165431094.jpg)
![a](https://user-images.githubusercontent.com/43179913/135906159-0a0f7fa8-18d7-415b-a5d6-79a188d050a0.jpg)
![a](https://user-images.githubusercontent.com/43179913/135906262-d5d6e36b-f350-4b52-b445-7f939aa9dae6.jpg)

**Comment by jboarman** [comment]
These look amazing!

In the future, we can explore a more realistic blend that allows the black to seep through more, but that's an unnecessary complication for this initial release of the feature.

**Comment by proofconstruction** [comment]
This looks great, please submit the PR so we can get this in.

**Comment by shaheryar1** [comment]
This has been added

**Comment by proofconstruction** [comment]
Highlight feature added by @shaheryar1 in PR #107 :clap:

**Comment by jboarman** [comment]
This random JavaScript library called Rough Notation that I came across might serve as inspiration for future enhancements: https://roughnotation.com/

![image](https://user-images.githubusercontent.com/1108065/143068028-5d8fd6c6-1275-47f6-b653-bfda060e95f8.png)

**Comment by kwcckw** [comment]
> This random JavaScript library called Rough Notation that I came across might serve as inspiration for future enhancements: https://roughnotation.com/
> 
> ![image](https://user-images.githubusercontent.com/1108065/143068028-5d8fd6c6-1275-47f6-b653-bfda060e95f8.png)

I think this should serve as a good reference for us since we are already having some of the augmentations , and the effect in the page looks very nice too.

**Comment by shaheryar1** [comment]
This is really great! I can already see some of the following enhancements that we can adapt from this

- Repeating the markup on a specific word/line multiple times (as if someone moves the pencil forward->backward->forward).
- Adding  box, circles, and crossed-off markups
- Giving the option to add markup on a single word

**Comment by jboarman** [comment]
In general, we can improve the highlight feature by reducing the level of highlight color as it affects darker colors.   I would think that some version of applying a threshold could be used to select the darker colors from the original ink layer to be re-blended into the final effect.  There are surely several approaches to solve this, but that is just one thought for an approach.

![image](https://user-images.githubusercontent.com/1108065/144143429-35fdf31e-4597-49d0-9d92-21e989f462ca.png)

**Real-life examples**
![image](https://user-images.githubusercontent.com/1108065/144143026-b84266b3-6e8e-4d4b-9bb2-9de677236d01.png)
![image](https://user-images.githubusercontent.com/1108065/144144225-4338e71f-0236-4a9d-8de6-ca6eedd949e9.png)
![image](https://user-images.githubusercontent.com/1108065/144144298-338bc52c-8fd6-46a0-a4d9-ea4604be876e.png)
![image](https://user-images.githubusercontent.com/1108065/144142876-d90ac1fe-28d0-400c-9426-05de0209a480.png)
![image](https://user-images.githubusercontent.com/1108065/144142933-8d13141e-7656-43f3-899d-c99ee1973d96.png)

**Comment by kwcckw** [comment]
> In general, we can improve the highlight feature by reducing the level of highlight color as it affects darker colors. I would think that some version of applying a threshold could be used to select the darker colors from the original ink layer to be re-blended into the final effect. There are surely several approaches to solve this, but that is just one thought for an approach.

Actually this can be resolved by using different weights, or using the current `OverlayBuilder`. Several examples:

Current existing method:
![image](https://user-images.githubusercontent.com/52521979/144239536-b712eb5d-ecaa-4a55-ba71-44d2ef1ee858.png)


Current existing method with different weights:
![image](https://user-images.githubusercontent.com/52521979/144240429-f813d4ca-fdbc-4367-9ff3-a172a58ae07b.png)


with `OverlayBuilder` - overlay type `min`:
![image](https://user-images.githubusercontent.com/52521979/144239653-1465c72b-74cc-4166-8477-a5a733dd55e4.png)


with `OverlayBuilder` - overlay type `alpha`:
![image](https://user-images.githubusercontent.com/52521979/144240676-6c6083cc-b18f-44e8-8bea-2b4858a5a816.png)

I guess we need to try them out and see which one looks more "natural".

**Comment by proofconstruction** [comment]
When we select a region of pixels to draw the highlight over, can we just use that same range of pixels to draw on the paper layer, instead of over the post-layer?

This may require changing how we expose layers in the pipeline, since other forms of markup (underlining, for example) should really happen at the post layer.

**Comment by kwcckw** [comment]
> When we select a region of pixels to draw the highlight over, can we just use that same range of pixels to draw on the paper layer, instead of over the post-layer?
> 

Yes, this can be done, by looking at the code, the current algorithm overlay both the highlighted image and the input image:

     markup_img = cv2.addWeighted(overlay, 0.3, markup_img, 1 - 0.3, 0)

Where `overlay` is the image with highlighted colour, while `markup_img` is the image without colour. 

If we just want to highlight the paper, we would need to get the current paper layer(if any), and then highlight the paper layer instead of the input image, then both of them will be overlayed again when we merge ink and paper layer.

> This may require changing how we expose layers in the pipeline, since other forms of markup (underlining, for example) should really happen at the post layer.

Yea, we might need to separate the processes into multiple layers, and changing the pipeline too. But i think underlining, strikethrough should happen at ink layer instead of post layer?

**Comment by jboarman** [comment]
If there are interactions between the "ink" and "paper" layers, then the post phase seems like the proper place to apply such interactions.

For example, when looking very closely at some of the highlight options, you can see how the paper texture affects the highlighter.  But, really, even strikethrough can be affected by the texture of the paper if you look closely enough.  So, this can get very complicated if we go that far with it.

Since things have changed over time, I'd like to confirm the current state of this question: Can the ink layer currently host color and alpha transparency values?

If the ink layer can host color and transparency, then I imagine this transform could operate either in the ink or the post phases.  If not, it would be limited to the post phase.  Does that sound right to you all?

**Comment by kwcckw** [comment]
> Since things have changed over time, I'd like to confirm the current state of this question: Can the ink layer currently host color and alpha transparency values?

From our discussion here:

https://github.com/sparkfish/augraphy/issues/116#issuecomment-945130689

I've removed the ink layer constraint so now it is able to host both colour and alpha layer. So far i don't see any major issue, just we need to check whether the input image is single channel or multi channels before we apply any augmentation.

> If the ink layer can host color and transparency, then I imagine this transform could operate either in the ink or the post phases. If not, it would be limited to the post phase. Does that sound right to you all?

I think it can be both, but it should be better in ink layer, since if we are having some other ink layer augmentations, those ink layer augmentations might having "interaction" with the current Markup augmentation before the post layer and paper layer. Anyway,i will try this out later and see which one looks better in the actual output.
