### ISSUE TITLE
Example Camera Phone / Screen Pics -- SAMPLES ONLY 

### ISSUE THREAD

**Issue by jboarman** [sparkfish/augraphy#118]
## SAMPLES ONLY -- Pics from _Camera Phone_

Since images take a lot of real estate, this thread is dedicated to sample images related to artifacts observed when taking pics of documents or screens from a camera phone.  These sample images will be references for use in future reproductions.

Samples should represent distortions caused by:

1. camera phones taking pictures of documents; or
2. camera phones taking pictures of a video / screen display

NOTE: Though samples are not limited to paper-oriented sources, these pics serve the needs in developing text extraction from text-based "documents" which may be sourced from screens or displays.

**Comment by jboarman** [comment]
## Lens Glare / Flare Sample

Brighter light sources can cause streaky + hazy effect on a camera lens, commonly known as lens glare or lens flare.  The angles of the glare can vary and be singular or multiple glares at different angles.  (This may be why polarized lenses are used to reduce or eliminate such glare.)

Lens glare is often cause by bright light sources reflecting within the frame.  It can also occur when a lens is dirty with smudges or spots on the surface of the lens that can scatter light and cause unwanted reflections.

In this example, linear glare seems to have a blurry streak that extends brighter / lighter colors both _horizontally_ and at a _-45° angle_ (in this case) against the dark background.

### Subtle Lens Glare
![image](https://user-images.githubusercontent.com/1108065/137776778-80bcbb6d-6842-47e4-92da-9144f638fc28.png)

### Harder Edge Flares, Glares and Smudges
![image](https://user-images.githubusercontent.com/1108065/224505264-33ec8967-0d97-49a3-ac79-f1898db07e23.png)

**Comment by jboarman** [comment]
## Example with Moiré pattern
![image](https://user-images.githubusercontent.com/1108065/137776819-0c3c2ebc-e595-4f94-8834-9182713a7ad6.png)

**Comment by jboarman** [comment]
## Example change in focus based on depth from lense

![image](https://user-images.githubusercontent.com/1108065/137777385-0b238b4f-53cf-45b4-b4c5-5975c1d0f1b4.png)

**Comment by shaheryar1** [comment]
![badscreen](https://user-images.githubusercontent.com/43179913/140656616-14bcbba3-c721-4d4b-8776-b362f3c6218f.jpg)

**Comment by jboarman** [comment]
## Example of a Dirty Screen

![image](https://user-images.githubusercontent.com/1108065/224516722-2b965c49-7bdc-47b4-9429-8dc7eb459777.png)

**Comment by jboarman** [comment]
## Example ambient light or flash reflected from surface of paper

* shows texture of paper surface
* makes printed content almost unreadable where light is shining back to the camera, often from a camera phone's flash

![image](https://user-images.githubusercontent.com/1108065/157357690-74a19a80-d1e9-4648-b5dc-4dce2cbb5f07.png)
![image](https://github.com/sparkfish/augraphy/assets/1108065/c6238e78-99c2-4f88-88c1-e78e0c9ea6c8)

**Comment by jboarman** [comment]
This website applies a pattern overlay using CSS to get a pattern that looks a photo was taken from a screen.  There are might even be versions of generated patterns that could be double-applied to simulate moire patterns.

Overlaid Version of Image:
![image](https://user-images.githubusercontent.com/1108065/158859412-a73fafb4-8f8f-44cf-a53e-90b3e091bc74.png)

Original Image:
![image](https://user-images.githubusercontent.com/1108065/158859625-7faac15e-5fbd-4d2c-8158-e1eaf13f40bd.png)

Pattern Overlay (super tiny, almost invisible image b/t brackets): [ ![screen pattern](https://user-images.githubusercontent.com/1108065/158858459-830d5349-6841-4fd2-a81f-d80b27ebb0ae.png) ]

Source URLs:
https://www.normascafe.com/locations/
https://www.normascafe.com/spillover/proto/normascafe/images/design/pattern.png
https://www.normascafe.com/spillover/proto/normascafe/images/backgrounds/deliverytruck.jpg

**Comment by jboarman** [comment]
Lots of Maths about Moire:

https://www.spiedigitallibrary.org/journals/optical-engineering/volume-57/issue-03/030803/Moir%C3%A9-effect-in-displays-a-tutorial/10.1117/1.OE.57.3.030803.full?SSO=1

**Comment by jboarman** [comment]
## Reflection Example (screen capture with glare reflected from surface)

![image](https://user-images.githubusercontent.com/1108065/167880897-874e81b1-2b41-41a6-aa30-534710162171.png)

**Comment by jboarman** [comment]
![image](https://github.com/sparkfish/augraphy/assets/1108065/42b7f48d-6c2b-45c8-b660-0c2baa32b6a3)

**Comment by kwcckw** [comment]
Added Moire effect here:
https://github.com/sparkfish/augraphy/pull/413

Added LCDScreenPattern here:
https://github.com/sparkfish/augraphy/pull/419
