### ISSUE TITLE
Create New Bleed-Through Augmentation

### ISSUE THREAD

**Issue by jboarman** [sparkfish/augraphy#12]
**Bleed-through** is caused by the seeping of ink from the reverse side of the page, through the sheet of paper, and into the front side of the page.  This faint bleed-through effect can be seen from a duplex-printed document, ink pressed document, or simply a document scanned or copied from a thin paper source.

## Examples
![image](https://user-images.githubusercontent.com/1108065/124682836-5f929c00-de91-11eb-9943-d886d1eb4b35.png)
![image](https://user-images.githubusercontent.com/1108065/124684164-2ad41400-de94-11eb-9bfa-e0d7bb7dfe45.png)
![image](https://user-images.githubusercontent.com/1108065/124684319-71c20980-de94-11eb-864a-11955316f91e.png)

## Reconstructing Bleed-Through Example
Using these sample images, we can construct the intuition for how we can simulate the bleed-through effect:

1. **Fabricate a Back Side Image** -- Use the source image (Front Side) to create a copy of the same image that is flipped to represent the reverse side of the page (Back Side).  Since we don't have any other source of information to draw from, we are forced to derive a plausible reverse side by taking the front side and reversing it.  We should do some random vertical shift of the content so that the horizontal content is not exactly the same as the front side.
2. **Degrade Back Side Image** -- Apply something like an aggressive Ink Bleed effect to the Back Side image.  Then, erode the ink as well as other treatments to reduce the intensity of the ink.
3. **Merge the Front Side + Back Side** -- Combine the layers bank into a single ink layer to simulate the ink-bleed effect.

**FRONT**
![image](https://user-images.githubusercontent.com/1108065/124684402-aa61e300-de94-11eb-8dbf-92199a7d9d50.png)
**BACK**
![image](https://user-images.githubusercontent.com/1108065/124684410-b188f100-de94-11eb-9639-5355c8ea59f8.png)
**MERGED FRONT + BACK**
![image](https://user-images.githubusercontent.com/1108065/124684428-c06fa380-de94-11eb-8143-842480dcefe9.png)

**Comment by kwcckw** [comment]
Yes, i think this is a good idea, i will try on this later.

**Comment by kwcckw** [comment]
Is something like this looks good enough?

![image](https://user-images.githubusercontent.com/52521979/124734542-cecac780-df47-11eb-92f6-1568b49a9e7e.png)

**Comment by jboarman** [comment]
I think this sample looks great!

Can you provide some additional variety using other source images, and limit to B/W so that we can focus the evaluation on a more limited set of augmentations or effects?

**Comment by kwcckw** [comment]
Alright, i will open a pull request (#19) when it's done.

**Comment by jboarman** [comment]
https://www.isos.dias.ie/Sigmedia/Bleed_Through_Database.html

> _Bleed-Through Database_
> The images contained here form a database that is designed to be a resource for people working in the field of digital document restoration, and more specifically on the problem of bleed-through degradation. It consists of a set of 25 registered recto verso sample grayscale image pairs, taken from larger manuscript images, with varied degrees of bleed-through.
> 
> The crops were taken such that they would contain a sentence or phrase of text, in order to make tests on improved legibility possible. All images in the database are saved in tif format. The verso side of each image pair has been flipped horizontally and registered to the recto side so that bleed-through text on one side and corresponding foreground text on the other are aligned.
> 
> One of the main problems encountered when researching digital document restoration is that no ground truth exists. That is there is no available clean original document with which to compare restoration results. Therefore ground truth has to be obtained either by creating synthetic degraded document images with known ground truth, or by creating synthetic ground truth images for real degraded images. This database contains the latter; manually created foreground text masks for each image have been created and are included here.
