### ISSUE TITLE
Better image blending

### ISSUE THREAD

**Issue by proofconstruction** [sparkfish/augraphy#120]
[The DIVADID project](https://diuf.unifr.ch/main/hisdoc/divadid-document-image-degradation) and several others merge foreground and background images by converting both to the gradient domain first. This approach seems to be called "gradient domain fusion" and uses algorithms like [Poisson image blending](https://www.cs.jhu.edu/~misha/Fall07/Papers/Perez03.pdf) to accomplish realistic blends.

It would be great to evaluate a similar approach to blending foregrounds (generated with OverlayBuilder or retrieved with FigshareDownloader) within ImageOverlay. This blend effect should be optional so the default method of using transparency in the overlay is still available.

If the results look promising, we may consider also adding the effect to the AugraphyPipeline class for a different approach to blending the ink and paper layers.

These might help:
1. [Blending Images with OpenCV](https://docs.opencv.org/master/d5/dc4/tutorial_adding_images.html#gsc.tab=0)
2. [Gradient domain fusion in Matlab](https://github.com/mnkyl/gradient-domain-fusion)

**Comment by proofconstruction** [comment]
[This paper](https://hal.inria.fr/hal-02460891/document) uses a different approach involving binarizing the text layer, which we might also consider.

**Comment by kwcckw** [comment]
Yea, those approaches look better, let me go through them first.

**Comment by proofconstruction** [comment]
Better image blending was added with [this commit](https://github.com/sparkfish/augraphy/commit/265da7ba041bfacd011aa4295d6c31cc1b0429a0#diff-78fa71c482c4b8ca6d29776c99019087ee64e8975998c86c6e3b8b5ef750ebce).
