### ISSUE TITLE
how to cite augraphy in research paper?

### ISSUE THREAD

**Issue by gxlarson** [sparkfish/augraphy#143]
Hello,
My team has recently used augraphy in a research project and we're interested in citing it in a paper. Is there a preferred citation?

**Comment by proofconstruction** [comment]
I'd love to hear more about how you used augraphy in your research!

Here's a BibTeX block you can use to cite:
```
@software{The_Augraphy_Project_Augraphy_an_augmentation,
author = {{The Augraphy Project}},
title = {{Augraphy: an augmentation pipeline for rendering synthetic paper printing, faxing, scanning and copy machine processes}},
url = {https://github.com/sparkfish/augraphy},
version = {5.0.0}}
```

and here's the APA:
```
The Augraphy Project. Augraphy: an augmentation pipeline for rendering synthetic paper printing, faxing, scanning and copy machine processes (Version 5.0.0) [Computer software]. https://github.com/sparkfish/augraphy
```

**Comment by gxlarson** [comment]
Thanks!

My colleague and I (see #136) have a collection of clean "born digital" documents and want to transform them into images that look less clean, as if they were scanned. The purpose is to test out image-based document classifiers on new data to see if they are able to generalize.

Apologies for this forward question, but is there any plan on drafting up a paper around the augraphy project? It's a great tool and I think the research community would benefit from being exposed to it. If not, please consider it, and I'd love to be a part of any analysis and/or writing process --- I'm currently a PhD student myself and have published papers on tools previously.

**Comment by proofconstruction** [comment]
Closing this since the original question is answered and discussion has moved elsewhere.
