### ISSUE TITLE
I get the folding effect even when I don't use folding in my pipeline

### ISSUE THREAD

**Issue by mahmouddaif** [sparkfish/augraphy#145]
Hello, I currently created some custom pipelines, for example
```
def get_pipeline(self):
        ink = AugmentationSequence([InkBleed(p=self.InkBleed_p),
               BleedThrough(p=self.BleedThrough_p, alpha = self.alpha),
               Letterpress(p=self.Letterpress_p),
               OneOf(
                   [
                       LowInkRandomLines(use_consistent_lines=False, p = self.LowInkRandomLines_p),
                       LowInkRandomLines(use_consistent_lines=True, p = self.LowInkRandomLines_p),
                       LowInkPeriodicLines(use_consistent_lines=False, p = self.LowInkPeriodicLines_p),
                       LowInkPeriodicLines(use_consistent_lines=True
, p = self.LowInkPeriodicLines_p),
                    ],
                ),])
        paper = AugmentationSequence(
                [
                    PaperFactory(p=self.PaperFactory_p),
                    NoiseTexturize(p=self.auto_texturize_p),
                    Brightness(p=self.Brightness_p, range=(0.6,1.2)),
                ],
            )

        
        post = [PencilScribbles()]


        return AugraphyPipeline(ink, paper, post)
```

I am getting the folding effect as shown in this image. Is there a way to stop this effect? Thank you. 
![basic_table_101](https://user-images.githubusercontent.com/2827808/149867583-a449b2f1-8e60-4c12-bb33-f1d9f2f15614.png)
![basic_table_301](https://user-images.githubusercontent.com/2827808/149867788-8b9803d3-1a86-49b0-99b1-c4eb4aaacc89.png)

**Comment by kwcckw** [comment]
Could you send me the exact code and file so that i can reproduce the issue from my end?

I tried from my end using similar pipeline and set p=1, but not getting the mentioned issue:

![image](https://user-images.githubusercontent.com/52521979/149870541-4eb664cd-a06b-44fd-8872-5145041b5f24.png)

**Comment by mahmouddaif** [comment]
Sorry I figured out the issue, it's my mistake, thanks for your help.

**Comment by kwcckw** [comment]
> Sorry I figured out the issue, it's my mistake, thanks for your help.

Thanks for letting me know. 

Please let me know again if you encounter any bugs or issues, that would be very helpful for us to further improve the repo.
