### ISSUE TITLE
Add Stains Augmentation

### ISSUE THREAD

**Issue by proofconstruction** [sparkfish/augraphy#153]
We should figure out an augmentation for placing stains on a document image, which generates the stains itself.

This probably looks like 2 new functions in `augraphy.augmentations.lib`:
1. a function to generate a boundary for the stain
2. a function to color&darken the interior of the boundary generated by function 1

We can probably use the model [here](https://aip.scitation.org/doi/10.1063/1.4966992) to produce a realistic diffusion effect for function 2.

**Comment by proofconstruction** [comment]
To generate a boundary, we can choose a pixel in the image and make several particles `{p1, p2, ..., pn}` randomly walk starting at that pixel, for some number of cycles. The resulting points `{p1_final, p2_final, ..., pn_final}` will lie on the boundary. The Graham scan algorithm can then be used to generate the convex hull enclosing those points, which we can then smooth by drawing Bezier curves or cubic splines through the hull points.

**Comment by kwcckw** [comment]
I was testing on the effect earlier and was able to generate something like this:

![image](https://user-images.githubusercontent.com/52521979/152490006-d4e594db-34c3-4bdd-a4fe-ad89bd3d68cc.png)

Will something like this useful?

Actually I couldn't access the full paper above, so couldn't get much info from it.

**Comment by kwcckw** [comment]
This is now added in this pull request:
https://github.com/sparkfish/augraphy/pull/422
