### ISSUE TITLE
Serializing Pipelines

### ISSUE THREAD

**Issue by proofconstruction** [sparkfish/augraphy#156]
We should have some mechanism for serializing pipelines, so we can run them again. This can either be a way to write the whole object to a file or to exactly re-generate it on a subsequent run. We may already be able to accomplish the latter using the `__repr__` method; I think this is actually `__repr__`'s _raison d'être_

**Comment by jboarman** [comment]
_oui, c'est vrai_

**Comment by proofconstruction** [comment]
It turns out that the `pipeline.__repr__()` output and consistent settings for `random.seed` and `numpy.random.seed` are all we need.
