### ISSUE TITLE
Watermarks, Stamps, Seals Augmentation (e.g., “COPY” / “VOID” / “DRAFT”) 

### ISSUE THREAD

**Issue by jboarman** [sparkfish/augraphy#159]
Document-oriented **watermarks** are common and have several patterns that we can attempt to reproduce:

* large print overlaid on document, of varying fonts and weights
* printed often at angles, diagonal across the page, from bottom-left to upper-right corners (at least in the US); or it can simply be horizontally placed on the page
* sometimes makes document text illegible, but most often watermarks are lightweight to allow readability of original document
* sometimes the watermark is laid over the text, and sometimes it's under the text
* dithering (20% probability) or some level of alpha blending (75% prob) is common, if not solid (5% prob)
* common watermark phrases: COPY, VOID, DRAFT, CONFIDENTIAL, UNOFFICIAL, DO NOT COPY, SAMPLE, ORIGINAL
* text is usually in UPPERCASE, but sometimes Title Case, or lowercase
* watermark may be some degree of grey (85% probability), red (10% prob) or any random color (5% prob)
* sometimes has border (like it was a stamp) or partial border (just lines at top and bottom of text) (5% prob, each)
* the same logic applied using smaller "watermarks" at more varied angles could suffice to double this augmentation as a "stamps" augmentation (see #129)

![image](https://user-images.githubusercontent.com/1108065/155234766-34916fc9-a91d-4e27-9870-3e56d264f02b.png)
![image](https://user-images.githubusercontent.com/1108065/155235859-b68b4973-a740-43ee-8fd6-a0d72c7ea174.png)

# Other kinds of Watermarks (Not immediately in Scope)

These other kinds of watermarks most associated with stock photos, or premium paper / historical documents when held up to a light source, is NOT part of the scope of this ticket, at least not initially.
![image](https://user-images.githubusercontent.com/1108065/155235362-facb2e7f-f007-44e7-8dd6-1d5ff3c7edf5.png)
![image](https://user-images.githubusercontent.com/1108065/155236099-ab9f4576-97a2-4299-8f17-c4cc55cc4517.png)

**Comment by jboarman** [comment]
For future reference, below are sources of stamp and seal datasets which might inspire a future dataset appropriate for adding stamps to document images.  These are NOT directly usable without further processing to add alpha transparency masks:

_**MiikeMineStamps Dataset** (05 May 2021)_
https://kilthub.cmu.edu/articles/dataset/MiikeMineStamps_Dataset/14604768
The MiikeMineStamps dataset is an open-ended dataset in the domain of Japanese historical documents. It contains 5056 images of Japanese stamps belonging to 407 classes, including two special classes. The stamps were extracted from historical documents from Mitsui Mi’ike Mine, a large business archive in modern Japan spanning over half a century and comprising tens of thousands of documents. The dataset is widely used by labor historians, business historians, and others interested in Japanese history.

_**Loay & Maha Stamps Dataset** (26 Feb 2020)_
https://data.mendeley.com/datasets/ktr99fc826/3
Contains 1557 color stamp samples in BMP image format and were acquired using scanners and mobile cameras and then cropped using software such as paint, snip, and sketch. Each cropped stamp has eight rotated images produced from rotating the original image from 5 to 40 degrees. The stamps come in different sizes, shapes, complexities, positions, directions, and colors, with six categories of shapes including circle, oval, square, rectangular, triangular, and irregular shapes. The dataset was collected from various sources, including official documents from Iraqi educational institutions and syndicates, as well as from other Arab countries.

_Freepik Searchable Stamp Images (Free)_
https://www.freepik.com/free-photos-vectors/stamp

_Pixabay Searchable Stamp Images (Free)_
https://pixabay.com/vectors/search/stamp/

_Wikimedia Commons (Public Domain, Raster Images)_
https://commons.wikimedia.org/w/index.php?search=stamp+images&title=Special:MediaSearch&go=Go&type=image&haslicense=unrestricted

_Icon Pack_
These permissively-licensed icon packs include thousands of images that could potentially be used as a source for creating "seals" and "stamps", at least in a loose sense.  For example, these could be processed with a letterpress type effect and have an appearance of a random stamp or seal.
https://github.com/react-icons/react-icons#icons

**Comment by jboarman** [comment]
## Uneven Ink Application
Stamp shows uneven application of ink, including some partial shifting/duplication of the stamp's ink:
![image](https://user-images.githubusercontent.com/1108065/230796611-76aa0419-0769-4af3-8bb6-6053704d8d9a.png)

**Comment by jboarman** [comment]
## Degraded Ink Seal

![image](https://github.com/sparkfish/augraphy/assets/1108065/901f17f9-7206-42ab-9853-6e73076b33b7)

ref: https://jivp-eurasipjournals.springeropen.com/articles/10.1186/s13640-021-00556-4

**Comment by kwcckw** [comment]
This is now added with this update:
https://github.com/sparkfish/augraphy/pull/171
