### ISSUE TITLE
Faxify Colab breaking

### ISSUE THREAD

**Issue by jdegange** [sparkfish/augraphy#173]
When running colab notebook, breaks after install and doesn't complete with example image file. 

See link in https://github.com/sparkfish/augraphy/blob/b2903e572ba55df1c9d79a2a599b77e9f9b0db92/doc/augmentations/faxify.md

Can submit PR, just let me know.

~~~python
ink = []

paper = []

post = [Faxify(
    scale_range=(1, 1),
    monochrome=0,
    monochrome_method="Otsu",
    monochrome_threshold=127,
    invert=1,
    half_kernel_size=2,
    angle=45,
    sigma=2,
    p=1
    )]

pipeline = AugraphyPipeline(ink, paper, post)
~~~

stack trace
~~~shell 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-6-4e6fef988594>](https://localhost:8080/#) in <module>()
     12     angle=45,
     13     sigma=2,
---> 14     p=1
     15     )]
     16 

TypeError: __init__() got an unexpected keyword argument 'monochrome_threshold'
~~~

when rm monochrome_threshold param from call:

~~~shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-8-465e19614d17>](https://localhost:8080/#) in <module>()
      1 clean = cv2.imread('clean.png')
      2 
----> 3 dirty = pipeline.augment(clean)['output']

2 frames
[/usr/local/lib/python3.7/dist-packages/augraphy/augmentations/faxify.py](https://localhost:8080/#) in __call__(self, image, layer, force)
    260 
    261                 half_kernel_size = random.randint(
--> 262                     self.half_kernel_size[0],
    263                     self.half_kernel_size[1],
    264                 )

TypeError: 'int' object is not subscriptable
~~~

**Comment by kwcckw** [comment]
Hi, looks like you are using the previous version of the library, could you try to install the latest version of augraphy in colab using this line?

    !pip install git+https://github.com/sparkfish/augraphy

**Comment by jboarman** [comment]
@kwcckw Is this an indicator that we need to issue a new release relatively soon?

**Comment by kwcckw** [comment]
> @kwcckw Is this an indicator that we need to issue a new release relatively soon?

Yes, i think the current version should be quite stable now.

**Comment by kwcckw** [comment]
@jdegange It should be installing the latest version 8.0 from pip install now, I will now close the issue and just let me know again if you are still facing the error.
