### ISSUE TITLE
Add Augmentation to Degrade Thin Lines in Irregular Manner

### ISSUE THREAD

**Issue by jboarman** [sparkfish/augraphy#176]
This poorly captured image demonstrates an effect with older documents where thin lines often degrade when copied.  We can't use a simple erode/dilate approach.  Instead, we need a technique similar to the Bad Photocopy augmentation that  applies the degradation in clusters that fade in and out across the document image.

![image](https://user-images.githubusercontent.com/1108065/172263965-1ad77c82-ac29-4e78-badb-37ad35cfa092.png)

**Comment by jboarman** [comment]
## Thinning and Thickening of Lines Example
Here's another example, in this case the thinning is much less strong.  But this also shows another behavior where the lines can thicken in the darker areas of the image.  Those darker areas tend to aggregate around the lines in those patches as well.

![Image](https://user-images.githubusercontent.com/1108065/232537130-5c2ae12d-476b-49fd-bb3d-642779b394cc.png)

**Comment by kwcckw** [comment]
This is now resolved with this pull request:
https://github.com/sparkfish/augraphy/pull/275
