### ISSUE TITLE
Add documentation in a dedicated hosting site.

### ISSUE THREAD

**Issue by kwcckw** [sparkfish/augraphy#179]
I think it will be better if there's a proper documentation site instead of having the documentation inside the github repo.

**Comment by samaymaini** [comment]
I believe we wanted all of the documentations in the github repo since it is easily accessible from the actual code and to anyone looking at the library. However, if we house this library somewhere else, we will definitely make a website for the documentation.

**Comment by jboarman** [comment]
Most of the popular open source libraries are using auto-generated documentation that is built based on the repo.  We should find a good model repo to copy their pattern.  ReadTheDocs offers a free option for open source, but perhaps there are others we should consider when the time is right.

**Comment by kwcckw** [comment]
> auto-generated documentation that is built based on the repo

Okay, and i think this will be a better choice instead of rewrite the whole documentations, so probably we can list down some of the reference repo who use this kind of documentation first.

**Comment by kwcckw** [comment]
The latest documentation is added here:

https://the-augraphy-project-augraphy.readthedocs-hosted.com/en/latest/
