### ISSUE TITLE
Add Batch Processing Functionality

### ISSUE THREAD

**Issue by kwcckw** [sparkfish/augraphy#180]
Right now the augmentation pipeline process single image at one time, it will be better if there's a batch processing function to process multiple images at one time.

**Comment by proofconstruction** [comment]
Do you mean something like this?

``` python
img1 = cv2.imread('image1.png')
img2 = cv2.imread('image2.png')
img3 = cv2.imread('image3.png')

pipeline.augment([img1,img2,img3])
```

**Comment by kwcckw** [comment]
Yes, so the pipeline should run across multiple images and generate randomize effect on each image.

**Comment by jboarman** [comment]
@kwcckw Can you elaborate on the interface signature that is needed to fulfill this requirement?  Also, is there anything needed here to make Augraphy work better with other pipelines such as PyTorch or TensorFlow, etc?

**Comment by kwcckw** [comment]
I think it could be similar with `imgaug` where the augmentation pipeline is able to accept batches of images. In their example, their pipeline is able to receive multiple images and process them in a single pipeline:

   https://imgaug.readthedocs.io/en/latest/source/examples_basics.html
   
Right now Augraphy accept only colored image `(ysize, xsize, channels)` or grayscale image `(ysize, xsize)`. We can have another preprocessing step to check if the input format is multiple images and apply the pipeline sequentially. Typically those multiple images input format can be in `(number_images, ysize, xsie, channels)` or a list contains multiple colored or grayscale images.

To allow Augraphy work better with Pytorch and Tensorflow, I think we will need to test run it by having Augraphy pipeline in those deep learning frameworks' dataloader. We can further improvise Augraphy if there's any issue or problem by running Augraphy pipeline in their dataloader. Then, we can include some examples on the steps to use it in our doc too, similar with `Albumentations`:

https://albumentations.ai/docs/examples/tensorflow-example/
https://albumentations.ai/docs/examples/pytorch_semantic_segmentation/

**Comment by jboarman** [comment]
@kwcckw I see #267 mentions implementation of batch processing in the pipeline.  Does this fully address the concerns raised in this issue?  Is there any new documentation or examples that can show how this can integrate with a dataloader for one of the DNN frameworks?

**Comment by kwcckw** [comment]
> @kwcckw I see #267 mentions implementation of batch processing in the pipeline. Does this fully address the concerns raised in this issue? Is there any new documentation or examples that can show how this can integrate with a dataloader for one of the DNN frameworks?

Yes, but the integration with deep learning will be tested and implemented on the next step. Right now we support batches of images, they can either in list of images or 4D images. I added examples here:
https://github.com/sparkfish/augraphy/blob/dev/examples/Augraphy_usage_examples.ipynb

**Comment by jboarman** [comment]
Thanks @kwcckw.  I've created a separate issue for a later sprint to deal with creating dataloader examples (#271).
