### ISSUE TITLE
add a .__version__ variable?

### ISSUE THREAD

**Issue by gxlarson** [sparkfish/augraphy#184]
I installed augraphy using `pip install augraphy` today and tried:

```
import augraphy
augraphy.__version__
```

to try to see the package version. Many (most?) python packages have this variable defined, as it can be helpful for debugging package issues.

See also: https://stackoverflow.com/questions/458550/standard-way-to-embed-version-into-python-package

**Comment by kwcckw** [comment]
Thanks for pointing this out. Yea, i agree we need this and it will be very helpful for the debugging process in the future. I will add this in the next update.

**Comment by kwcckw** [comment]
This is now resolved with this commit: https://github.com/sparkfish/augraphy/commit/2f14d1c9850f6ca41b9e8b020ca5f3c53fdacf51

I will now proceed to close the issue.
