### ISSUE TITLE
Pipeline printing

### ISSUE THREAD

**Issue by xingjianz** [sparkfish/augraphy#191]
Small problem but the pipeline prints only the ink_phase as shown.
https://github.com/sparkfish/augraphy/blob/2f58a48dc324fb653965374a9a9ac5a0dfdb475a/augraphy/base/augmentationpipeline.py#L302-L304

**Comment by kwcckw** [comment]
Thanks! I will fix this in the next update.

**Comment by kwcckw** [comment]
This is fixed in this pull request: https://github.com/sparkfish/augraphy/pull/192/.
