### ISSUE TITLE
Inconsistent error when running example with BirghtnessAugmentation

### ISSUE THREAD

**Issue by kwcckw** [sparkfish/augraphy#2]
Hi,

I'm facing an inconsistent error with the added brightness augmentation, here's the snippet of my code:

        pipeline = default_augraphy_pipeline()
        pipeline.ink_phase.augmentations.append(BrightnessAugmentation('ink'))
        
        paper_factory = pipeline.paper_phase.augmentations[0]
        paper_factory.probability = 1.0
        
        jpeg_aug = pipeline.post_phase.augmentations[-1]
        jpeg_aug.quality_range = (10, 20)
        
        img = np.array(create_pdf417())
        crappified = pipeline.augment(img)
        
        
        for i in range(10):
            crappified = pipeline.augment(img)

Upon checking, looks like image are not always returned in bgr (3 channels) from the AugmentationResult although the input is in 3 channels:

error source:
![image](https://user-images.githubusercontent.com/52521979/123400870-ca61ee80-d5d8-11eb-98a0-d70e5670a30d.png)

error exact line:
![image](https://user-images.githubusercontent.com/52521979/123400584-80790880-d5d8-11eb-98c0-a7d6c0a1dc2c.png)

Could you check on this?

Thank you.

**Comment by shaheryar1** [comment]
Hi @kwcckw . Thanks for highlighting this.
The BrightnessAugmentation adjusts the brightness using HSV space. It can be applied to any phase (ink, paper,post) using `self.layer` argument.
But the "ink" phase inputs the image as Grayscale image with 1 channel only. Hence, its not compatible with  `hsv = cv2.cvtColor(img.astype("uint8"),cv2.COLOR_BGR2HSV)` . It should be first converted into BGR format. 
```
 def __init__(self, layer, range=(0.8, 1.4), probability=0.5):
    super().__init__(probability=probability)
    self.range = range
    self.layer = layer
```
I have adjusted the code, and I will push it in my PR. @jboarman

**Comment by kwcckw** [comment]
> 
> 
> Hi @kwcckw . Thanks for highlighting this.
> The BrightnessAugmentation adjusts the brightness using HSV space. It can be applied to any phase (ink, paper,post) using `self.layer` argument.
> But the "ink" phase inputs the image as Grayscale image with 1 channel only. Hence, its not compatible with `hsv = cv2.cvtColor(img.astype("uint8"),cv2.COLOR_BGR2HSV)` . It should be first converted into BGR format.
> 
> ```
>  def __init__(self, layer, range=(0.8, 1.4), probability=0.5):
>     super().__init__(probability=probability)
>     self.range = range
>     self.layer = layer
> ```
> 
> I have adjusted the code, and I will push it in my PR. @jboarman

Thanks, and in this case, since 'ink' phase input is in grayscale, probably we can just adjust the code similarly?

Right now i can see it is applied in saturation and value channel of hsv image, so if the input is grayscale, why don't we just apply it directly to the grayscale values?

**Comment by shaheryar1** [comment]
Yes this can also be done , as for single channel images to increase brightness we can tweak the saturation channel only.

**Comment by kwcckw** [comment]
> 
> 
> Yes this can also be done , as for single channel images to increase brightness we can tweak the saturation channel only.

Sorry but how can we get saturation channel in single channel image? Merge same single channel image to bgr ( 3 channels of grayscale) , convert them to hsv and adjust the saturation channel?

**Comment by shaheryar909** [comment]
Yes you are right @kwcckw . We have to convert grayscale into bgr to get the saturation channel and adjust it.

**Comment by kwcckw** [comment]
> 
> 
> Yes you are right @kwcckw . We have to convert grayscale into bgr to get the saturation channel and adjust it.

Alright thanks for the clarification again.

**Comment by tbrettallen** [comment]
Merge request has been approved and merged into the dev branch. Change has been deployed to version 2.0.4 of augraphy on pypi.
