### ISSUE TITLE
The documentation is not rendering

### ISSUE THREAD

**Issue by LucianoBatista** [sparkfish/augraphy#200]
When I access the doc site (https://the-augraphy-project-augraphy.readthedocs-hosted.com/en/latest/) I'm getting a page with this:

```
        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
           ]                     [   /  |
           ]___               ___[ ,'   |
           ]  ]\             /[  [ |:   |
           ]  ] \           / [  [ |:   |
           ]  ]  ]         [  [  [ |:   |
           ]  ]  ]__     __[  [  [ |:   |
           ]  ]  ] ]\ _ /[ [  [  [ |:   |
           ]  ]  ] ] (#) [ [  [  [ :===='
           ]  ]  ]_].nHn.[_[  [  [
           ]  ]  ]  HHHHH. [  [  [
           ]  ] /   `HH("N  \ [  [
           ]__]/     HHH  "  \[__[
           ]         NNN         [
           ]         N/"         [
           ]         N H         [
          /          N            \
         /           q,            \
        /                           \

```

**Comment by kwcckw** [comment]
Thanks for pointing this out. We migrated the doc site recently and yet to update the readme here. Right now here's the new doc site:
https://augraphy.readthedocs.io/en/latest/

**Comment by LucianoBatista** [comment]
Nice, now works 🎉 !

And thank you for this package, will be really useful on a project that I'm working on 😉 !

**Comment by kwcckw** [comment]
> Nice, now works 🎉 !
> 
> And thank you for this package, will be really useful on a project that I'm working on 😉 !

You are welcome. Please let us know if you encounter any issue, it will be very helpful for us to further improve the library.

**Comment by kwcckw** [comment]
The documentation site should be updated with this commit:
https://github.com/sparkfish/augraphy/commit/be8e544db1836f584d562f21400030ba873cd85b

I will now proceed to close the issue.
