### ISSUE TITLE
How to apply same pipeline to input and target image?

### ISSUE THREAD

**Issue by vscv** [sparkfish/augraphy#204]
Is there a way to use the same pipeline on input and target images? For example, when bookbinding/folding should remain the same as the input and target images.

**Comment by kwcckw** [comment]
Do you mean to use a same pipeline to 2 images (input and target)?

It should be possible and you just need to set the pipeline' augmentation's probability to 1 to prevent any missing augmentation.

For example:

      ink_phase   = [Folding(p=1)]
      paper_phase = []
      post_phase  = [BookBinding(p=1)]
      pipeline    = AugraphyPipeline(ink_phase, paper_phase, post_phase)

**Comment by vscv** [comment]
Thank you, @kwcckw, but the randomizing of each augmentation will change when applying pipeline.augment().

```
# sample pipeline

ink_phase = [

]

paper_phase = [

]

post_phase = [
    Folding(
        fold_x=None,
        fold_deviation=(0, 0),
        fold_count=random.randint(1, 6),
        fold_noise=random.uniform(0, 0.2),
        gradient_width=(0.1, 0.2),
        gradient_height=(0.01, 0.02),
        p=1,
    ),

    BookBinding(
        radius_range=(1, 100),
        #curve_range=(100, 200),
        mirror_range=(0.3, 0.5),
        p=1,
    ),
]

pipeline = AugraphyPipeline(ink_phase, paper_phase, post_phase)

in_clean_img = "2.bmp"
in_clean_img_2 = "2cleaned.bmp"

img = cv2.imread(in_clean_img)
img_2 = cv2.imread(in_clean_img_2)

data = pipeline.augment(img)
data_2 = pipeline.augment(img_2)

augmented = data["output"]
augmented_2 = data_2["output"]

plt.figure(figsize=(10,10))
plt.imshow(augmented)

plt.figure(figsize=(10,10))
plt.imshow(augmented_2)
```
[augmented input]
![Imgur](https://imgur.com/qdpQnUk.jpg)
[augmented target]
![Imgur](https://imgur.com/YaAeAd3.jpg)

**Comment by kwcckw** [comment]
At this point, to give consistent output, you will need to define all input arguments and use a same value range, for example:

    Folding(
            fold_x=50,
            fold_deviation=(0, 0),
            fold_count=random.randint(3, 3),
            fold_noise=random.uniform(0.1, 0.1),
            gradient_width=(0.1, 0.1),
            gradient_height=(0.01, 0.01),
            p=1,
        )
        
This will be the same for the other augmentations too. However, there are still some randomized internal parameters within some other augmentations too. If you still facing randomness after defining a same set of values, that's mean those are the randomness from internal parameters and right now we don't have random seed implemented yet. This will be included in the next few updates.

**Comment by vscv** [comment]
@kwcckw, thanks for the tip. Now I think I know how it works.
