### ISSUE TITLE
Markup augmentation not working on IAM lines dataset

### ISSUE THREAD

**Issue by cs-mshah** [sparkfish/augraphy#207]
I tried to apply a markup augmentation with the following parameters on the `lines/a01/a01-000u/a01-000u-06.png` image from the [IAM lines dataset](https://fki.tic.heia-fr.ch/DBs/iamDB/data/lines.tgz), but it didn't seem to create a strikethrough.

Original:
![a01-000u-06](https://user-images.githubusercontent.com/56499208/201627046-2ecba3ee-8e28-45b0-bf05-ee3675dbb592.png)

Markup: `Markup(markup_color=(0, 0, 255), repetitions=4,
                single_word_mode=True, markup_type="strikethrough")`:

![marku](https://user-images.githubusercontent.com/56499208/201627407-c8a78237-910a-4e85-bf32-2c5638ef0a19.png)

What parameter changes should I make?

**Comment by kwcckw** [comment]
At this moment, to prevent `Markup` apply on large text ,we limit it to small size text only (compare to size of image) so no Markup augmentation will be applied on your image for now.

Thank you for letting us know and we will include an update on this soon. 

So if you want to try it with your current image, you may change the code in Markup:

1. In line 240, change it to `if check_height:`
![image](https://user-images.githubusercontent.com/52521979/201686307-137b544b-91cd-4f8b-9643-bd7bf575a0c5.png)

2. Remove line 243 and 244:
![image](https://user-images.githubusercontent.com/52521979/201687355-dec949ca-e341-461e-a90d-07a4cbd9b200.png)


Then you will get something like this:
![image](https://user-images.githubusercontent.com/52521979/201687531-a223da4b-30dd-4b46-a222-b0de9dbba8d6.png)

**Comment by kwcckw** [comment]
This should be fixed with the latest update. So you can reinstall Augraphy and set `large_word_mode` to True in `Markup` augmentation to enable the effect in your image above. Please let me know again if you still didn't get any markup effect.

**Comment by cs-mshah** [comment]
Got the same issue as: https://github.com/sparkfish/augraphy/issues/208#issuecomment-1315768792
