### ISSUE TITLE
rel and dev branches out of sync

### ISSUE THREAD

**Issue by proofconstruction** [sparkfish/augraphy#222]
rel needs to be kept in-sync with dev, within a few commits

**Comment by jboarman** [comment]
To try to address issue, we have created a GitHub project board.  Our goal should be to release at least as often as an iteration.  For now, I've set up the iteration to be 4-week sprints.  This should help us set expectations and openly prioritize the issues.  The iterations will help us also ensure that we are merging the `dev` branch into `rel` periodically, which should trigger a new release to be published to PyPI.

**[Augraphy Roadmap](https://github.com/orgs/sparkfish/projects/8)**

**Comment by kwcckw** [comment]
> To try to address issue, we have created a GitHub project board. Our goal should be to release at least as often as an iteration. For now, I've set up the iteration to be 4-week sprints. This should help us set expectations and openly prioritize the issues. The iterations will help us also ensure that we are merging the `dev` branch into `rel` periodically, which should trigger a new release to be published to PyPI.
> 
> **[Augraphy Roadmap](https://github.com/orgs/sparkfish/projects/8)**

In this case, is it fine if I merge them in every end of the month? Or last week of the month?

**Comment by jboarman** [comment]
It's fine to merge anything you feel we have an update worthy of a release, but in general we can assume that each iteration should end with a release.
