### ISSUE TITLE
Callable pipeline

### ISSUE THREAD

**Issue by erik-koynov** [sparkfish/augraphy#238]
It will be nice to make the pipeline object callable instead of having to call .augment() (as are the torchvision transforms or the imgaug transforms).

**Comment by kwcckw** [comment]
Hi Erik Koynov,

Thanks for the suggestion. We will look into this.

**Comment by kwcckw** [comment]
This should be fixed in this pull request now:
https://github.com/sparkfish/augraphy/pull/240
