### ISSUE TITLE
Develop Augmentations that Simulate Images Taken by Camera Phone

### ISSUE THREAD

**Issue by jboarman** [sparkfish/augraphy#239]
We are maintaining a set of _sample images taken by camera phones_ (see #118), often including of those taken of a monitor or display.  Those samples drive this list of augmentations needed to simulate the needed features.

Additionally, here is an example dataset that could be used to source features to simulate document images taken by camera phones.
https://www.researchgate.net/publication/349818385_A_Document_Image_Dataset_for_Quality_Assessment

![image](https://user-images.githubusercontent.com/1108065/221902133-3ca153f2-43ee-4df7-9f8a-f81a1122b9a9.png)

## Various Features of Camera-Phone Pictures

Separate issues are tracking the various features that are needed:
* Moiré Patterns for Screen Pics (#91)
* Low-Light Noise (#158)
* Depth-Simulated Blur (#421)
* Double-Exposure Blur (#414)
* Dirty Screen Display (dirt and smudges on computer screen)  (#415)
* Lens Glare / Flares (#417)
* Reflected Glare (with optional surface texture for paper sources) (#291)
* Shadows (#266)

**Comment by kwcckw** [comment]
Depth-Simulated Blur is added here:
https://github.com/sparkfish/augraphy/pull/421

Double-Exposure Blur is added here:
https://github.com/sparkfish/augraphy/pull/414

Dirty Screen Display (dirt and smudges on computer screen) is added here:
https://github.com/sparkfish/augraphy/pull/415

Lens Glare / Flares is added here:
https://github.com/sparkfish/augraphy/pull/417
