### ISSUE TITLE
Add support for Albumentations and Imgaug Transforms

### ISSUE THREAD

**Issue by jboarman** [sparkfish/augraphy#25]
Instead of reinventing the wheel, we should allow transforms from [Albumentations](https://github.com/albumentations-team/albumentations) and [Imgaug](https://github.com/aleju/imgaug) libraries to be callable within an augraphy pipeline.  In general, our pipeline process should be familiar to a user of Albumentations, so in theory this should be an easy adaptation to support their transforms in an Augraphy pipeline.

In general, we should provide basic transforms which may be defined in these libraries which are needed for the common document-oriented augmentations.  So, we'll have some minimal overlap; however, we should **not** _require_ these other libraries for the default and most common augmentation needs.

**Note** that Albumentations currently seems to be well maintained while Imgaug has not been updated in a little over a year as of this moment.  So, we should prioritize Albumentations over Imgaug.  It appears that Imgaug has additional blur transforms, which can be useful to vary since deblurring of basic gaussian blur is fairly easily learnable using deep learning methods; but we should not invest too much effort in supporting a library that is not being maintained.

**Comment by kwcckw** [comment]
From a quick glance at [Albumentations](https://github.com/albumentations-team/albumentations) , those should be related to digital side of the augmentation and should be more low level if we compare it to the existing augmentations. If we want to support them in the current work, i think the best way is to enable the usage of those libraries in each phase augmentation sequence pipeline, for example:

ink_phase = AugmentationSequence([
    MedianBlur(),
    RandomFog()])
    
But there's some issues need to be resolved since they are from different base classes, or is there a better way to do this?

**Comment by jboarman** [comment]
> But there's some issues need to be resolved since they are from different base classes, or is there a better way to do this?
> 

We should be able to check the type info on the transforms supplied to the pipeline and handle that based on compliance with the interfaces that those methods expose, all _without_ actually depending on those libraries within our `requirements.txt`.

**Comment by proofconstruction** [comment]
I'm cleaning things up for a PR now, but I'll test this afterwards. I expect it already works as intended, since all of our augmentations treat image data as `numpy.array` objects, and so does every other package I've seen in this space.

I'll drop an example here in a little bit.

**Comment by proofconstruction** [comment]
This was very easy. We can't directly use Albumentations or Imgaug augmentations within our pipeline, but we can expose simple wrapper classes which convert them to our own, and these can be added directly to our pipeline.

For example, using Albumentations:

```

class AlbumentationToAugraphyAugmentation(Augmentation):
    """A wrapper for Albumentation augmentations."""

    def __init__(self, layer, albumentationAugmentation, p=0.5):         
        self.layer = layer                                               
        self.augmentation = albumentationAugmentation                    
        super()__init__(p=p)                                             

    def __call__(self, data):                                            
        image = data[self.layer][-1].result                              
        result = self.augmentation(image = image)["image"]               
        data[self.layer].append(AugmentationResult(self, result)

```

I think it'd be great to add a module for wrappers like this; future feature requests to support interoperability with other augmentation libraries would be as simple as adding a new wrapper class, and would not require us to formally depend on these other libraries.

**Comment by proofconstruction** [comment]
I did it. The latest commit [here](https://github.com/sparkfish/augraphy/commit/9ea0502516606f1bc73b4067b18955308b7c6332) adds a module providing a wrapper class `ForeignAugmentation` which can be used in our pipeline. This does not require any additional dependencies.

You use this just like any other Augraphy augmentation, but pass in the constructor for the Albumentations/imgaug augmentation like so (here's a piece of a modified default pipeline):

```
import albumentations as A
from imgaug import augmenters as iaa
...


    post_phase = AugmentationSequence([DirtyRollersAugmentation(p=0.0),
                                       OneOf([
                                           LightingGradientAugmentation(),
                                           BrightnessAugmentation('post')
                                       ]),
                                       SubtleNoiseAugmentation(),
                                       ForeignAugmentation("post", A.RandomGamma(), p=0.5),
                                       ForeignAugmentation("post", iaa.Fliplr(p=0.5),  p=1), 
                                       JpegAugmentation()
                                       ])
```

**Comment by jboarman** [comment]
This worked out great!

If we ever need to have any explicit optional reference to an external library, I came across this [code from Albumentations](https://github.com/albumentations-team/albumentations/blob/0f76247d70eb7aecc8b8e6e95fb3661eb58c1fd3/tests/conftest.py#L18-L29) that seems to handle that cleverly:

```
try:
    import imgaug

    imgaug_available = True
except ImportError:
    imgaug_available = False


skipif_imgaug = pytest.mark.skipif(imgaug_available, reason="The test was skipped because imgaug is installed")
```

Then [with some tests](https://github.com/albumentations-team/albumentations/blob/0f76247d70eb7aecc8b8e6e95fb3661eb58c1fd3/tests/test_imgaug_imports.py#L65-L69) (just as an example of the concept), this was used to control whether external references were accessed:

```
from tests.conftest import skipif_no_imgaug, skipif_imgaug

@skipif_no_imgaug
def test_iaaperpective_augmentation_imported_when_imgaug_is_installed():
    from albumentations.imgaug.transforms import IAAPerspective

    t = IAAPerspective()
    assert isinstance(t, A.DualTransform)
```
