### ISSUE TITLE
Project Logo for Augraphy

### ISSUE THREAD

**Issue by jboarman** [sparkfish/augraphy#26]
We need a project logo.

Creating logos is usually pretty hard.  But the process usually starts with identifying words or phrases that relate to the identity being represented.

What ideas do you have for how to represent what Augraphy is doing with the fewest number of impactful words as possible?

**Starter Phrases / Thoughts / Words**
1. renders synthetic paper printing, faxing, scanning and copy machine processes 
2. clean input images are turned into dirty and realistic document images
3. pipeline that applies various adjustments to a clean original in order to create realistic dirty data for training
4. creates paper-oriented augmentation data
5. synthetic, simulates reality, realistic, distortion
6. pipeline, machine, cog in a process, factory, assembly line
7. forged documents

**Questions for Discussion**
What other thoughts and ideas go into your concept of what Augraphy is about?  How would you reduce these thoughts into more succinct descriptions?  How would you visualize some of these ideas?

Once everyone has a chance to provide input, I'll share a first round of logos for reaction.

**Comment by kwcckw** [comment]
In term of sentence, i would think  `Create realistic paper texture`.

Some impactful words for me are:

1. Realistic
2. Augmentation
3. Synthetic

> What other thoughts and ideas go into your concept of what Augraphy is about? How would you reduce these thoughts into more succinct descriptions? How would you visualize some of these ideas?

When i think of Augraphy, the first thing is my mind is creating more augmented samples from existing real life sample. In our current case, those samples are usually texts and sentences with background serve as the 'paper'. A precise and clear words to describe this probably would be just **augmented paper writing**.

**Comment by proofconstruction** [comment]
As a logo image, I’m imagining an outline of a hand holding a pen, with the tip of the pen at the end of the tail of the Y in `Augraphy`. The characters in the word `Augraphy` start clean but get progressively more pixelated and deformed (InkBlob, DustyInk, JPEG artifacts, …) towards the end of the word, and the hand appears to be “dissolving” in the same way.

For a cheeky slogan: “real fake documents”

**Comment by shaheryar1** [comment]
For the sentence the best way to describe would be "Synthesizing dirty, realistic, and old documents using clean documents".
For logo I really likes the idea provided by @proofconstruction because this way our logo can visually describe the purpose of Augraphy .

**Comment by kwcckw** [comment]
> Once everyone has a chance to provide input, I'll share a first round of logos for reaction.

So those initial round of logos are available now?

**Comment by jboarman** [comment]
I'm not quite happy with these yet, but here are the first sets of logo options.  At this point, we should pick 1 or 2 candidates from this list to refine as well as consider an altogether different concept as an alternate to have designed:

https://docs.google.com/document/d/e/2PACX-1vSCluKX-q2gNW18o2q3P2q2D41XOSN416iCdtKEg103b7BFH0xPsejnPrl22Ph3FvmxKdGE8tueFlJe/pub

Please share comments and reference the logo number in your comments (e.g., _"`#0` is great because..."_, or _"`#0` is not quite right because..."_).

**Comment by proofconstruction** [comment]
I think `#5` is perfect. The logo is a nice flat image (ironic) that perfectly describes what the library does; the arrow goes from a "clean" paper to an augmented one, and the outline of the image is reminiscent of a document icon in a file browser, suggesting this transformation happens purely digitally. The arrow makes this much better than `#4`, because the dual arrows there might imply that the library can be used to _de-augment_ (denoise, deblur, etc) documents, which is not in scope.

`#6` is my second choice, because the shape is suggestive of scanning or printing or otherwise doing _something_ to a paper with a physical machine, but isn't actually a recognizable shape like `#7`.

I _really_ like the purple and gray of `#3`, as well as the font and stylization of "augraphy". I'd like to see a blend of `#3`, `#5`, and `#6`, where the document-file-icon shape from `#5` is being fed into the abstract machine box of `#6`, and the bottom half of the file icon gets the letterpress effect. This would look really striking if the outline of the file icon was in the purple of `#3` and the letterpress result was colored with the `#3` gray. The rectangle for the machine box could just be black.

**Comment by kwcckw** [comment]
I would think either number 5 or number 3, since a logo with half augmented paper would be more relatable. The other's doesn't stand out so much at my first glance. Additionally, are those word "Augraphy" below the logo is part of the logo too?

**Comment by shaheryar1** [comment]
I think number 2 represents the purpose of augraphy. As it is getting a document converting it to different forms. Moreover, it looks kind of decent to me provided that font is changed.

**Comment by jboarman** [comment]
The design competition was a success.  We got a large variety of logos.  Polling was done to get general feedback on the logos.  Final selection was made with guidance from an independent, profressional graphic designer.

# Winner
![image](https://user-images.githubusercontent.com/1108065/130331184-13d203d4-7d8f-4b80-b01e-82123f35920f.png)


# Runner Ups

There are other clear winners, but unfortunately we must choose only one.  The sexiest logo has the most mainstream appeal, but it doesn't tell the story quite as well as others.  The simplest logo looks great at small scale, but it doesn't look so great when used in large scale, such as for the header on the main GitHub README.  The most descriptive logo might be a bit too complicated.  And the most cerebral logo evoked thoughts of an HVAC coil to some.

![image](https://user-images.githubusercontent.com/1108065/130331203-2ba37b6c-8757-4b8d-aeb4-6d4503eceeeb.png)

**Comment by kwcckw** [comment]
Nice !
