### ISSUE TITLE
Add Augmentation for Shadows Cast onto Camera-Sourced Document Images

### ISSUE THREAD

**Issue by jboarman** [sparkfish/augraphy#266]
For #239, we need to add support for shadows.  As seen in the DDI-100 dataset and many others involving camera phone sources, shadows often come from the shape of the phone and hands of the person taking the picture or potentially other sources of light cast onto the document image being taken.

![image](https://user-images.githubusercontent.com/1108065/230239972-ccf19fc2-77cf-4ca9-a8b3-85a90b201eab.png)
[![image](https://user-images.githubusercontent.com/1108065/231888736-7c4197f7-74a8-4d9e-ad70-17b06fb611e1.png)](https://dib.cin.ufpe.br/docs/DocEng21_bin_competition_report.pdf)

Reference: https://www.researchgate.net/publication/368522020_A_Quality_Size_and_Time_Assessment_of_the_Binarization_of_Documents_Photographed_by_Smartphones

**Comment by kwcckw** [comment]
This is now added in this pull request: https://github.com/sparkfish/augraphy/pull/290.
