### ISSUE TITLE
Create Example Using Dataloader for PyTorch and TensorFlow

### ISSUE THREAD

**Issue by jboarman** [sparkfish/augraphy#271]
We need to provide an example notebook that shows how to create a dataloader that leverages Augraphy and is leveraged by PyTorch and Augraphy.  Presumably that is sufficient for use with other libraries like Keras, PyTorch Lightning, etc. 

These should each be in their own notebook within the `examples` folder.

**Comment by kwcckw** [comment]
The examples are now added in this pull request: https://github.com/sparkfish/augraphy/pull/286.
