### ISSUE TITLE
Add Python 3.11 Support, Drop Python 3.7

### ISSUE THREAD

**Issue by jboarman** [sparkfish/augraphy#273]
Python is dropping all support for **3.7** in the next few months, which is only limited to security updates anyhow.  So, we should drop that from our build and test scripts.

At the same time, we should also add support for **3.11** and include that in the build steps in `tox` to verify 3.11 support with each push to the repo.

**Comment by kwcckw** [comment]
From this discussion:
https://github.com/numba/numba/issues/8304

`numba` wasn't supported in 3.11 earlier, but looks like it's just fixed last week. I will need to verify and test it against 3.11 first before including 3.11 in repo.

**Comment by kwcckw** [comment]
I tried but facing error in installing numba in 3.11. Also I found this discussion:
https://numba.discourse.group/t/can-not-install-numba-and-llvmlite-to-python-3-11/1651

So looks like it's not supported yet and we can migrate to 3.11 later once they are supported.
