### ISSUE TITLE
Images Broken in PyPI Listing

### ISSUE THREAD

**Issue by jboarman** [sparkfish/augraphy#279]
We need to fix the broken image references, which may involve the following solution:

> _Why do image references break when published to PyPI from the README.md in GitHub?_
> 
> PyPI may not include images in the package: When you publish a package to PyPI, PyPI only includes the files that are explicitly listed in your package's setup.py or setup.cfg file. If your README.md file references images that are not explicitly included in your package, then those images will not be included in the PyPI distribution.
>
> To ensure that your images are displayed correctly on PyPI, you should use absolute paths to reference the images in your README.md file, and you should ensure that the images are included in your package's setup.py or setup.cfg file.

NOTE that the example images were uploaded as usercontent.  However, that means references are not local to the repo as they should be.  So, we should attempt to maintain the images locally to the repo and see if including those files in the setup resolves the issue.

![image](https://user-images.githubusercontent.com/1108065/234066652-44bc33f7-b22d-4414-bdd9-303d019f8ac0.png)

**Comment by kwcckw** [comment]
From this pull request, I updated the image reference by using web link so now the main issue should be resolved:
https://github.com/sparkfish/augraphy/pull/281

Also there's still a minor issue in the example image, probably is due to it is using a different format in referencing the image, i will change that in the next update to pypi.

**Comment by kwcckw** [comment]
This is now resolved with this pull request:
https://github.com/sparkfish/augraphy/pull/283
