### ISSUE TITLE
Reflected Light from Camera Flash or other Bright Sources

### ISSUE THREAD

**Issue by jboarman** [sparkfish/augraphy#291]
### Lighting Sources
- [ ] Nearby sources, such as lamps or overhead lighting (creates distinct, defined reflections)
- [ ] General ambient lights (produces diffuse, soft-edged reflections)

### Effects
- [ ] Glare spots from reflective surfaces (e.g., glass, shiny paper) that can fully or partially obscure content
- [ ] Softly illuminated larger shapes or glowing areas, possibly encircling glare spots, resembling reversed shadows, mildly obstructing content; glass surfaces such as a computer screen may exhibit sharper edges in reflections; (the effect may be similar to shadows, except in reverse)
- [ ] Reflected glare revealing surface texture (for paper sources, not screen displays) by reflecting white/light colors that obscure content along the raised portions of the surface texture

#### Shiny Paper
![image](https://user-images.githubusercontent.com/1108065/157357690-74a19a80-d1e9-4648-b5dc-4dce2cbb5f07.png)
#### Shiny Photo Paper or Glass
![image](https://github.com/sparkfish/augraphy/assets/1108065/c6238e78-99c2-4f88-88c1-e78e0c9ea6c8)
#### Computer Display
![image](https://user-images.githubusercontent.com/1108065/167880897-874e81b1-2b41-41a6-aa30-534710162171.png)

**Comment by kwcckw** [comment]
This is now done in this pull request: https://github.com/sparkfish/augraphy/pull/293.
