### ISSUE TITLE
Add Color Shifting / 3D Blur Effect

### ISSUE THREAD

**Issue by jboarman** [sparkfish/augraphy#296]
This effect involves a sort of double or triple printing of the ink layers, printed from different channels that are shifted and blurred.

The color shifting / 3D blur effect involves these steps:

1. split channels from original source (either RGB or CMYK or HSV)
2. randomly keep color or convert to grey scale or recolorize to a different shade
3. shift split channels to randomly adjust placement, shifting X/Y positions by random offset and random directions for each channel; most often, channels will go in opposite directions from each other, but might not
4. most often, reduce intensity of split channels (Poisson-likely to reduce intensity); often adding in a mild blur to one or more split layers
5. most often, retain the original layer and blend with other split layers; otherwise, print only the split layers

Some additional inspiration might come from tutorials like this one on how to do the similar "glitch effect" in photoshop step-by-step: https://pixelbuddha.net/journal/tutorials/how-to-create-glitch-effect-in-photoshop

![image](https://github.com/sparkfish/augraphy/assets/1108065/37aae1b2-4f2b-4564-935a-36ebd35abbe7)

![image](https://github.com/sparkfish/augraphy/assets/1108065/55b7a3c0-c71e-4d7a-b414-95ba1e981d06)

**Comment by kwcckw** [comment]
From this pull request: https://github.com/sparkfish/augraphy/pull/302, this should be added now.

**Comment by jboarman** [comment]
@kwcckw Can you demo how we can apply this augmentation to reproduce the image above where the colors are like shadows echoing the text above and below the line in slightly different shades?

**Comment by kwcckw** [comment]
> @kwcckw Can you demo how we can apply this augmentation to reproduce the image above where the colors are like shadows echoing the text above and below the line in slightly different shades?

The shadow like effect is only applicable for grayscale image only since those displaced color will be in grayscale now and hence creating a shadow like effect. Some grayscale examples:

![image](https://github.com/sparkfish/augraphy/assets/52521979/a78060fb-c421-430c-9e0f-91a3f0bc87d1)
![image](https://github.com/sparkfish/augraphy/assets/52521979/b9652e2b-cf71-4a78-b046-da538d9ab0bd)
![image](https://github.com/sparkfish/augraphy/assets/52521979/e01b3b1a-932d-4b5c-ab94-b2175cbfdca2)

**Comment by jboarman** [comment]
Thank @kwcckw.  After we finish the other 2 new augmentations (#304 and #303), then we can come back and do the channel splitting so that we can get that effect on black/grey ink layers.
