### ISSUE TITLE
Add adapter for `imagecorruptions`

### ISSUE THREAD

**Issue by jboarman** [sparkfish/augraphy#30]
Just as we provide adapters for `imgaug` and `albumentations`, the `imagecorruptions` is another library we could add support for:

https://github.com/bethgelab/imagecorruptions

For some reason, they claim this library is not built for augmentations, but this library is being used by `imgaug`.  Further, this library seems to be maintained while `imgaug` has not been touched in over a year.

**Comment by proofconstruction** [comment]
Good news: `imgaug` uses these in [this module](https://github.com/aleju/imgaug/blob/master/imgaug/augmenters/imgcorruptlike.py), wrapping them in `imgaug` augmenters. Those can be used with our `ForeignAugmentation` wrapper already, and `imgaug` actually already supports all of them (compare the `imgaug` class list [here](https://github.com/aleju/imgaug/blob/master/imgaug/augmenters/imgcorruptlike.py#L19) with the list of `imagecorruptions` [here](https://github.com/bethgelab/imagecorruptions/blob/master/imagecorruptions/__init__.py#L24)). The best code is the code we don't have to write!

I updated the README to reflect our support for these.
