### ISSUE TITLE
Add `InkColorSwap` to Replace the Color Used for Lettering in a Document

### ISSUE THREAD

**Issue by jboarman** [sparkfish/augraphy#303]
Historical documents, as just one scenario, often have text that is faded or otherwise have low contrast compared to the background.  Since it can be difficult to source documents that meet this criteria, we need an augmentation that can be used to render these scenarios.

### Effect of `InkColorSwap` Augmentation

* Randomly select contours of glyphs/letters
* Randomly extend the contour selection to neighboring glyphs (horizontally-close contours) that approximate selecting words
* Swap the color of the contours to a randomly-fixed color for the whole document _or_ a random color for each contour

# Reference Images
Note the effect of the red and black text in examples below.  The examples illustrate these effects where (1) the red ink has a lower contrast than the black ink compared to the background color, (2) the red ink has faded more than the black over time, and (3) when converted to greyscale the red ink almost disappears since it lacks the color contrast to differentiate the ink from the ~paper~ papyrus.

## Red / Black Ink (crisp, but low contrast compared to background)
![image](https://user-images.githubusercontent.com/1108065/244133889-de0ec14e-e352-4e43-a2e4-a58e36446e66.png)

## Red Ink Faded More than Black Ink
![image](https://user-images.githubusercontent.com/1108065/244133763-d7260d89-9b08-4978-8fd7-f61afaed16ab.png)

## Greyscale Version Illustrating Impact of Low Contrast Colors
![image](https://user-images.githubusercontent.com/1108065/244133856-1f0b86fb-05d2-40af-bc5f-c66b45bd9f16.png)

**Comment by kwcckw** [comment]
This is now added in this pull request:
https://github.com/sparkfish/augraphy/pull/305
