### ISSUE TITLE
Add `InkMottling` Augmentation to Ensure Ink is Non-Uniform

### ISSUE THREAD

**Issue by jboarman** [sparkfish/augraphy#304]
To render real-world documents, ink sourced from a perfect PDF source should not render as perfect black, for example.  Such examples are _easily_ denoised with threshold filters.  So we need to add noise to the incoming ink layer.

## Effects of `InkMottling` Augmentation
* [ ] The existing ink layer is adjusted by a noise layer
* [ ] The noise could be composed of positive and negative numbers (useful when ink is not strictly black or white) so that levels are adjusted both up and down
* [ ] Noise options would start with fast noise options like `Poisson` or `Gaussian` or `Speckle` noise  ([see deprecated code from skimage](https://github.com/scikit-image/scikit-image/blob/359d4e360d3a6dc489c45a2a33c6bd5fe6b3908d/skimage/util/noise.py#L42-L231))
* [ ] The range of noise values effecting ink should be parameterized -- by default, this range should be low and subtle, often un-noticeable to the human eye unless you are looking for it
* [ ] The noise layer should randomly apply to either all channels, or be independent noise applied separately to each channel (to simulate black rendered by color ink)

## Example Problem Image (what this augmentation will fix)
![image](https://github.com/sparkfish/augraphy/assets/1108065/d90c42cc-a153-4b38-9c68-e0b34ebdf1ee)

## Example Real-World Mottling of Black Ink
![image](https://github.com/sparkfish/augraphy/assets/1108065/7418c36d-5872-4072-b841-616ff29acaf1)

**Comment by kwcckw** [comment]
This is now added in this pull request:
https://github.com/sparkfish/augraphy/pull/305
