### ISSUE TITLE
Update to Paper Factory

### ISSUE THREAD

**Issue by ss756** [sparkfish/augraphy#312]
# Problem Statement

Currently, in our Augraphy repo we have a proper paper phase where we overlay textures on top of the images.
However, we have recognized the need to create more extensive and diverse set of textures to further enhance the quality and variability of synthetic data generated by Augraphy. To address this, we are thinking to generate additional textures by manipulating the existing set of diverse textures through addition, subtraction and multiplication of their features.

# Extract Features from Each Texture for Texture Manipulation

## Feature Extraction

- **Haralick Features:** Haralick features are a good way to distinguish between different textures. These texture features quantify the feel, appearance, or consistency of a surface.
- Additional features like **color histograms** can also be used to extract features and generate the synthetic dataset.

## Blending

- **Addition and Subtraction:** Combine the features of two textures by adding or subtracting corresponding feature values. Experiment with different weightings or scaling factors to control the intensity of the manipulation.
- **Feature Multiplication:** Multiply selected features from one texture with features from another texture to generate unique combinations.

## Texture Synthesis

- The **Efros-Leung Algorithm** looks promising for generating new textures.

## Links

- Adding (Blending) two images in OpenCV: [Tutorial](https://docs.opencv.org/3.4/d5/dc4/tutorial_adding_images.html)
- Alpha Blending using OpenCV (Python): [Tutorial](https://learnopencv.com/alpha-blending-using-opencv-cpp-python/)
- Haralick texture features: [Resource](https://gogulilango.com/software/texture-recognition)
- Haralick texture | Computer Vision: [Article](https://cvexplained.wordpress.com/2020/07/22/10-6-haralick-texture/)
- Efros and Leung Texture Synthesis (berkeley.edu): [Resource](https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/resources.html#texture)
- Efros and Leung Texture Synthesis Algorithm (GitHub): [Repository](https://github.com/rbaravalle/efros)
- Generating textures from scratch (Stackoverflow): [Resource](https://stackoverflow.com/questions/51646185/how-to-generate-a-paper-like-background-with-opencv)

![image](https://github.com/sparkfish/augraphy/assets/61051785/6054470f-27ec-44b0-9062-6dc59d393784)

**Comment by kwcckw** [comment]
This is now added in this pull request:
https://github.com/sparkfish/augraphy/pull/313
