### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by proofconstruction** [sparkfish/augraphy#32]
In the course of the past two weeks, I’ve already pushed a few commits that introduced bugs, or outright broke things. As the project grows and changes, debugging will increase in difficulty, and accordingly increase the potential for these errors.

To help mitigate this, I’d like to introduce proper unit and property tests (right now, we only have a script called “test”, which isn’t actually a test), and add these to the pre-commit git hooks to help ensure quality of commits.

Albumentations has a few [here](https://github.com/albumentations-team/albumentations/blob/master/.pre-commit-config.yaml) using the [pre-commit-hooks project](https://github.com/pre-commit/pre-commit-hooks) that we could take inspiration from, but mostly these are code style checks. I’d really like to have some testing at the level of - for example - “make sure these two numpy arrays have dimensions that allow them to be multiplied”, which would’ve saved me time and the need to make [this correction](https://github.com/sparkfish/augraphy/pull/31/commits/a7b4e7ad9dbf8ec318902fe2119142bd5d4a814d) in PR #31

**Comment by kwcckw** [comment]
Yea,  i do agree we need a proper test script but with the rapid development and changes from the current repo, if we add in a test script now, it might become obsolete again very soon. Unless the test script is general enough to allow tests with some major changes, and it would be good if it is capable to detect runtime error and static error too.

**Comment by jboarman** [comment]
I suggest a very simple start on this.  Eventually we should make the tests run using GitHub Actions, but getting a very small and basic set of tests will be a huge step in and of itself.  Integrating these as a required step triggered as part of the PR process _may_ be a slightly less frustrating process than using pre-commit hooks to run tests.

**Comment by proofconstruction** [comment]
GH Action to lint and run a simple pytest was added with [this commit](https://github.com/sparkfish/augraphy/commit/01422b2b5df840bd7ba808af90321b6e8db3c344).
