### ISSUE TITLE
Confusion on `Geometric` Augmentation

### ISSUE THREAD

**Issue by what-in-the-nim** [sparkfish/augraphy#320]
# Description
When using the `Geometric` augmentation, I encountered confusion on the `randomize` keyword argument and its interaction with other arguments. The current behavior is that when initializing the `Geometric` class, the `randomize` argument, which defaults to `True`, overrides all other arguments that are not explicitly passed in during initialization. This behavior seems to differ from what I initially assumed, where I expected all other arguments to be set to their default values if not provided.
```python
# Geometric __init__
def __init__(
        self,
        scale=(1, 1),
        translation=(0, 0),
        fliplr=0,
        flipud=0,
        crop=(),
        rotate_range=(0, 0),
        padding=[0, 0, 0, 0],
        padding_type="fill",
        padding_value=(255, 255, 255),
        randomize=1,
        p=1,
    )
```
## Steps to reproduce
```python
augmentation = Geometric(rotate_range=(-4,  4))
augmented = augmentation(image)
```
## Original Image
![original](https://github.com/sparkfish/augraphy/assets/67754293/f9f988e0-a93f-4f09-a0ba-0d1503e053a4)

## Current Behavior
![output_weird](https://github.com/sparkfish/augraphy/assets/67754293/ecf4f907-dee6-4bcf-a67a-a8bdf78466f5)

## Expected Behavior
![output](https://github.com/sparkfish/augraphy/assets/67754293/36faa8fa-d256-4103-a6ec-e422e8b27c9c)

## Proposed Solution
I suggest setting the `randomize` argument to `False` by default, as it would provide a more intuitive behavior.

Please note that this issue is based on my understanding of the current behavior. If my assumptions are incorrect, please provide clarity on the intended behavior of the `Geometric` augmentation class.

**Comment by kwcckw** [comment]
Thanks for the feedback. We have `randomize` set as True for some other application. So when `randomize` is True, it overwrites all the other parameters. We will look into this further and change it accordingly.

**Comment by kwcckw** [comment]
In the newer releases, we have `randomize` set as false now. Please feel free to let us know again if you have other related feedback.
