### ISSUE TITLE
Add Jupyter Notebooks to demonstrate pipelines for business use cases and demos

### ISSUE THREAD

**Issue by shaheryar1** [sparkfish/augraphy#33]
For the starters there must an interactive way to see how to create and use different **Augraphy** pipelines. Multiple Jupyter Notebooks, each representing a different use-case can serve this purpose.

**Comment by kwcckw** [comment]
I'm thinking to use augraphy to further improve the work in old document restoration, since those documents are quite rare and it would be helpful if we are able to produce some synthetic samples to further aid in their model training process. 

Example of old document restoration:
https://arxiv.org/pdf/2001.08742.pdf

Do you guys think this is a good idea?

**Comment by kwcckw** [comment]
> 
> 
> I'm thinking to use augraphy to further improve the work in old document restoration, since those documents are quite rare and it would be helpful if we are able to produce some synthetic samples to further aid in their model training process.
> 
> Example of old document restoration:
> https://arxiv.org/pdf/2001.08742.pdf
> 
> Do you guys think this is a good idea?

I tried to create some old documents by using different fonts and papers. Here are the current results:

![img5](https://user-images.githubusercontent.com/52521979/126865350-a55ca074-3800-4b6d-bb10-9d82d6809ed1.png)
![img6](https://user-images.githubusercontent.com/52521979/126865353-5dc7e529-1092-4032-b24b-65a4c20086f5.png)
![img7](https://user-images.githubusercontent.com/52521979/126865356-4f4be833-5622-48da-b692-494aed6623b4.png)
![img8](https://user-images.githubusercontent.com/52521979/126865358-6669462c-70a7-4481-b28b-6e431b436fce.png)
![img9](https://user-images.githubusercontent.com/52521979/126865359-da0f2c71-a687-4b7a-9870-68dc42cab7dc.png)
![img1](https://user-images.githubusercontent.com/52521979/126865360-f0d65a52-4df4-4ecf-850d-97513930517f.png)
![img2](https://user-images.githubusercontent.com/52521979/126865363-e092125a-46d6-47c2-9746-0410fd3b22d7.png)
![img3](https://user-images.githubusercontent.com/52521979/126865364-34f0bf21-d0a3-4544-a53f-52e8e594397f.png)
![img4](https://user-images.githubusercontent.com/52521979/126865365-bf352dd4-2bb5-40ed-bc37-a0be885f9e03.png)

Is this real enough? Or do let me know if you think there's any area of improvement.

One of the constraint right now is the page is in perfect condition, it would be nice if we can create some teared paper effect.

**Comment by kwcckw** [comment]
I added a demo here using google colab:
https://colab.research.google.com/drive/1g0hDeneIGcy0sYtIzZSnNmZfesFdu5Sn?usp=sharing

**Comment by jboarman** [comment]
Thanks @kwcckw 

Can you update that notebook to use [`gdown`](https://github.com/wkentaro/gdown)?

Once you've compiled all the files into a Google Drive folder, then you will need to file IDs for each file: https://clay-atlas.com/us/blog/2021/07/01/python-en-gdown-package-download-file-google-drive/

If we are sharing more than a few files, then it might be best to ZIP the files together first so that it's a single file to be downloaded and unpacked within the notebook.

**Comment by kwcckw** [comment]
> 
> 
> Thanks @kwcckw
> 
> Can you update that notebook to use [`gdown`](https://github.com/wkentaro/gdown)?
> 
> Once you've compiled all the files into a Google Drive folder, then you will need to file IDs for each file: https://clay-atlas.com/us/blog/2021/07/01/python-en-gdown-package-download-file-google-drive/
> 
> If we are sharing more than a few files, then it might be best to ZIP the files together first so that it's a single file to be downloaded and unpacked within the notebook.

Thanks, i will look into this and apply the changes accordingly.

**Comment by kwcckw** [comment]
I added a new example with gdown, now user will be able to download files and run the same thing from their end. Is there anyone can try this out and let me know if this is run-able?

Link: https://colab.research.google.com/drive/1IDkfmKKajMb2dlchW-rWN6kmrnGk2TWX?usp=sharing

i just tried with another account and with a new copy of notebook, so far there's isn't any issue yet and please let me know if you guys facing any problem to run the notebook.

![image](https://user-images.githubusercontent.com/52521979/127127715-c9da594e-db49-494e-93eb-9bf463c08090.png)

**Comment by jboarman** [comment]
Can you remove all dependency on connecting to a personal Google Drive (outside of using `gdown` I mean)?

For example, we should be able to just use the local folder on the Colab server instead mounting the “My Drive” reference.

**Comment by kwcckw** [comment]
> 
> 
> Can you remove all dependency on connecting to a personal Google Drive (outside of using `gdown` I mean)?
> 
> For example, we should be able to just use the local folder on the Colab server instead mounting the “My Drive” reference.

Alright, at this point i'm not aware of such function yet, let me check again.

**Comment by kwcckw** [comment]
Here's the updated notebook which is able to run without connecting to any gdrive, but you still need to login to your google account to run it:
https://colab.research.google.com/drive/1MXNhPQ_37aiPmAOkfKNCDhKnlaPc1zDt?usp=sharing

Also if the code is updated in the pip installation , then we can skip the section to download the zip file too.

**Comment by kwcckw** [comment]
I added new notebook on the example of pipeline for photocopy paper, and I've updated the previous example on old document to use the code directly from the repo. So right now there's 2 examples from my end:

1. Photocopy paper:
https://colab.research.google.com/drive/1hLHyyvNi-cRRDOcqtPnZPCw4j25oZMDG?usp=sharing

2. Old document:
https://colab.research.google.com/drive/1MXNhPQ_37aiPmAOkfKNCDhKnlaPc1zDt?usp=sharing

**Comment by tbrettallen** [comment]
> 1. Photocopy paper:
>    https://colab.research.google.com/drive/1hLHyyvNi-cRRDOcqtPnZPCw4j25oZMDG?usp=sharing

I'm having an issue running this notebook. I've attached the issue I've run into in the image below.
![PencilScribblesSubtleNoise](https://user-images.githubusercontent.com/3762313/130094892-08f4343e-c6b5-45e0-b78c-d04f68653d77.png)

**Comment by kwcckw** [comment]
> 
> 
> > 1. Photocopy paper:
> >    https://colab.research.google.com/drive/1hLHyyvNi-cRRDOcqtPnZPCw4j25oZMDG?usp=sharing
> 
> I'm having an issue running this notebook. I've attached the issue I've run into in the image below.
> ![PencilScribblesSubtleNoise](https://user-images.githubusercontent.com/3762313/130094892-08f4343e-c6b5-45e0-b78c-d04f68653d77.png)

Sorry, it should be caused by a typo in the init file. Now i updated the code and tested it. It should be having no issue to run now.

**Comment by proofconstruction** [comment]
I get a type error running this.
![2021-08-27-160614_3840x2160_scrot](https://user-images.githubusercontent.com/74747193/131094590-581fd16e-7c2a-4039-891f-e901a37642f6.png)

**Comment by kwcckw** [comment]
> 
> 
> I get a type error running this.
> ![2021-08-27-160614_3840x2160_scrot](https://user-images.githubusercontent.com/74747193/131094590-581fd16e-7c2a-4039-891f-e901a37642f6.png)

Sorry, this notebook is still pending update, since it is using the previous badphotocopy code. I will post here again when it is updated.

**Comment by kwcckw** [comment]
> Sorry, this notebook is still pending update, since it is using the previous badphotocopy code. I will post here again when it is updated.

@proofconstruction I just updated the notebook, please try again and let me know if you facing any issue to run the notebook.

**Comment by proofconstruction** [comment]
These look really good!

Is the "Photocopy machine" code now part of `BadPhotoCopy`?

The "Synthetic old documents" code can probably become a new augmentation, or maybe a utility class. We should add a new Issue to discuss this.

**Comment by kwcckw** [comment]
> 
> 
> These look really good!
> 
> Is the "Photocopy machine" code now part of `BadPhotoCopy`?
> 
> The "Synthetic old documents" code can probably become a new augmentation, or maybe a utility class. We should add a new Issue to discuss this.

I think this should be a "pipeline level" demo where we apply several augmentations to produce a more relatable real life application. So eventually we can have several predefined pipelines (sort of utility class), each with different purpose, for example photocopy machine effect, old document effect, and etc (can't think of more now).

**Comment by proofconstruction** [comment]
> I think this should be a "pipeline level" demo where we apply several augmentations to produce a more relatable real life application. So eventually we can have several predefined pipelines (sort of utility class), each with different purpose, for example photocopy machine effect, old document effect, and etc (can't think of more now).

I like this idea, and I think we can use the pipelines for the [Reproducing Archetypes](https://github.com/sparkfish/augraphy/issues/74) work as the predefined ones. Once we get those working well, we can add them to `augraphy.default.prebuilt` or something, so users can select one of those or the `default_augraphy_pipeline` containing all augmentations.

**Comment by proofconstruction** [comment]
Closed with PR #154
