### ISSUE TITLE
Installation from source 

### ISSUE THREAD

**Issue by shaheryar1** [sparkfish/augraphy#37]
I saw that the code is upgraded and version is changed to 2.0.5. However, I can't find the installation instructions for developers from source. 
Can you please update about this ? @proofconstruction

**Comment by proofconstruction** [comment]
I'm not sure what you mean - do you still need help with this?

**Comment by shaheryar1** [comment]
No actually my older forked version was throwing import errors. I cloned the repo again and the issue was fixed
