### ISSUE TITLE
Typo in Readme example

### ISSUE THREAD

**Issue by kwcckw** [sparkfish/augraphy#4]
Hi,

In the readme, there's typo in paper factory:
![image](https://user-images.githubusercontent.com/52521979/124237612-4bc1ff80-db4a-11eb-90a6-01585be9eab1.png)

where "tile_texture_shape" should be just "texture_shape":
![image](https://user-images.githubusercontent.com/52521979/124237750-7318cc80-db4a-11eb-9216-87d12a3cd5cb.png)

**Comment by tbrettallen** [comment]
Thanks, this has been corrected. The code & readme are now in sync.
