### ISSUE TITLE
Warped text lines to give the effect of a book page

### ISSUE THREAD

**Issue by shaheryar1** [sparkfish/augraphy#44]
While scanning pages of books or a page from a document bundle sometimes the text lines can get warped like in the images below. Can we achieve this kind of effect using the existing augmentations in augraphy i:e **(page curl/elastic transform)** ? 

![A-few-example-images-of-curled-text-line-segmentation-using-coupled-snakelets-algorithm](https://user-images.githubusercontent.com/43179913/127297949-61920043-b959-4bc1-b322-d20d4f7dbd9d.png)
![Coupled-snakelets-features-illustration-of-evolving-and-weighted-coupling-nature-of-a (2)](https://user-images.githubusercontent.com/43179913/127297958-3dadbadf-59b0-4ab9-bdd7-f8ce10694c25.png)
![Capture](https://user-images.githubusercontent.com/43179913/127298106-47c1289c-6fdb-4234-a4fd-b213135b6662.PNG)

**Comment by proofconstruction** [comment]
I don't think we can do this with existing augmentations, but it's something I've been thinking about adding for a few days.

The [DocCreator paper](https://www.mdpi.com/2313-433X/3/4/62/pdf) explains a little about how they do something similar, on page 10 under _3.7. Nonlinear Illumination Model_. In that case, they're changing the brightness of part of the image to simulate the document curling away, as if in a book. We could use a similar function to move pixels in the `post` layer, to simulate the whole page warping.

**Comment by proofconstruction** [comment]
I don't think we can do this with existing augmentations, but it's something I've been thinking about adding for a few days.

The [DocCreator paper](https://www.mdpi.com/2313-433X/3/4/62/pdf) explains a little about how they do something similar, on page 10 under _3.7. Nonlinear Illumination Model_. In that case, they're changing the brightness of part of the image to simulate the document curling away, as if in a book. We could use a similar function to move pixels in the `post` layer, to simulate the whole page warping.

**Comment by kwcckw** [comment]
Yea, i think this could be an add-on on top of current folding augmentation?

I haven't got the chance to try it but i think elastic transform from albumentation should be helpful in this case:
https://albumentations.ai/docs/api_reference/augmentations/geometric/transforms/#albumentations.augmentations.geometric.transforms.ElasticTransform

**Comment by shaheryar1** [comment]
Started some experiments according to the method mentioned in **DocCreator paper** . I guess we should also also add the warped lines effect to make it look like a book page. 
Also what should be the name of this kind of augmentation ?

![download](https://user-images.githubusercontent.com/43179913/129230506-4ea3bf27-fb21-4e5d-bb39-085f0c75423b.png)

**Comment by proofconstruction** [comment]
The book binding shadow above looks pretty good, and we could include it in Augraphy, but maybe we should also have an effect that produces the transformations shown above.

**Comment by jboarman** [comment]
That's a perfect name ... "BookBindingShadow" ... not to be confused with _Binding Shadows_,  the first book in the _Tooth & Spell_ trilogy.  :mage:

**Comment by shaheryar1** [comment]
Added sin wave warping effect to generate the book folding effect along with binding shadow. What do you think about the following image generated with it ? 
Notebook : https://colab.research.google.com/drive/1TWMM6L8-AVdLrQp_Fyhlk7WRV87WVTuR?usp=sharing

![download (1)](https://user-images.githubusercontent.com/43179913/129731055-2f9d61d8-db95-4530-af97-d1e0b83bca53.png)

**Comment by kwcckw** [comment]
Looks great, so is it possible to generate a similar "cosine wave" warping effect?

**Comment by shaheryar1** [comment]
Yeah but cosine wave effects does not look realistic

**Comment by shaheryar1** [comment]
Created Pull Request #60  for this feature

**Comment by jboarman** [comment]
**DocUNet Benchmatch Dataset**
https://www3.cs.stonybrook.edu/~cvl/docunet.html

> Because large-scale real-world data with ground truth deformation is difficult to obtain, we create a synthetic dataset with approximately 100 thousand images by warping non-distorted document images. ... We further create a comprehensive benchmark that covers various real-world conditions. ... [the benchmark dataset] contains 3 parts: i) original photos, ii) document centered cropped images (used in our paper), and iii) scans from a flatbed scanner.

MATLAB code is included for performing the simulated mesh warp.

![image](https://user-images.githubusercontent.com/1108065/221914035-5b7b07a7-7aa2-4b3a-af14-08f71cf1f416.png)

**Comment by kwcckw** [comment]
I think **DocUNet** warping may be more relevant in another augmentation like elastic transform?

**Comment by jboarman** [comment]
That's a valid point.  I was thinking of page bends from a book being opened as being a special case of random page warping.  Once we have an alternative for wrinkle effects, maybe we only will need book binding to offer page warping.  Either way, I wanted to tag this as existing related work and the fact that there is a challenge dataset out there that we could reference to try to simulate these real-world (and simulated) document image transforms.
