### ISSUE TITLE
Add Bad Photocopy Texture Augmentation

### ISSUE THREAD

**Issue by kwcckw** [sparkfish/augraphy#45]
To add a similar effect from bad photocopy machine, for example:
![image](https://user-images.githubusercontent.com/52521979/127864985-25b40318-b4ab-4a26-a455-f3cd1782d0f2.png)
image source: https://www.kaggle.com/aravindram11/funsdform-understanding-noisy-scanned-documents

At this point, i think it can be done by adding small blobs of different size, and varying their area and frequency to reproduce a similar effect.

**Comment by shaheryar1** [comment]
Yes, but the blobs should be in a diminishing/increasing pattern. It can't be totally randomized over the whole page

**Comment by proofconstruction** [comment]
This effect can occur when the page doesn't make adequate contact with the scanner bed, or when the glass of the scanner bed has defects or dirt blocking the light path

I think this can be achieved with existing noise and inkblobs augmentations, if they're restricted to sections of the image. Maybe a brightness texturize for good measure.

**Comment by kwcckw** [comment]
Yea, i'm trying to create different patches of noises using `_create_blob` and `applyBlob`:

![image](https://user-images.githubusercontent.com/52521979/128010597-960e535a-23c6-4121-ba39-0525729f78b5.png)


But it should be better with blob size >1, right now those noises are in pixel level, each of them are having size==1, doesn't looks good yet.

**Comment by kwcckw** [comment]
I added variable size blobs, looks better now:
![image](https://user-images.githubusercontent.com/52521979/128166086-b0df7eaf-dc4c-4a41-8c99-d4051e548811.png)

> Yes, but the blobs should be in a diminishing/increasing pattern. It can't be totally randomized over the whole page

@shaheryar1  Yes, right now the example adding noises to 4 corners of image, so we would need to design different kind of noise pattern to make it more realistic. 

> Maybe a brightness texturize for good measure.

@proofconstruction I don't quite get this, could you elaborate further ?

**Comment by proofconstruction** [comment]
> > Maybe a brightness texturize for good measure.
> 
> @proofconstruction I don't quite get this, could you elaborate further ?

I just mean that the brightness of dots should also vary, in addition to their size. The bottom left corner of the original image has areas with a lighter form of the effect, which we could simulate by changing the brightness of the dots we apply in some area. This would give more variation to the effect than just the gaussian blobs, which look too "regular"

**Comment by kwcckw** [comment]
> 
> 
> > > Maybe a brightness texturize for good measure.
> > 
> > 
> > @proofconstruction I don't quite get this, could you elaborate further ?
> 
> I just mean that the brightness of dots should also vary, in addition to their size. The bottom left corner of the original image has areas with a lighter form of the effect, which we could simulate by changing the brightness of the dots we apply in some area. This would give more variation to the effect than just the gaussian blobs, which look too "regular"

Okay, but shouldn't be photocopy machine output is always black & white? So the intensity variation might not be relevant here.

**Comment by kwcckw** [comment]
I added several patterns for this augmentation effect:

1. Scattered noises:
![image](https://user-images.githubusercontent.com/52521979/128594706-e681ba05-fe0b-4921-a95a-2743f00a667b.png)

2. Random noises:
![image](https://user-images.githubusercontent.com/52521979/128594592-6247c782-7202-43f3-a541-02d1e6a9787d.png)

3. Corner noises:
![image](https://user-images.githubusercontent.com/52521979/128594624-92f65cf1-a790-49c5-980c-42db9954d02d.png)


A combination of them would looks like this:
![image](https://user-images.githubusercontent.com/52521979/128595040-32fc0103-6591-4d9f-b918-a66813a0d80b.png)

I think the challenging part is to make them looks natural, so any comment or suggestion based on the current output above?

**Comment by kwcckw** [comment]
I added the colab notebook demo here:
https://colab.research.google.com/drive/1zcLdFEikxrQRQLFFEXiqnw9efevldrid?usp=sharing

**Comment by proofconstruction** [comment]
Merged PR #50 solving this.
