### ISSUE TITLE
Streamline Composition, Remove "Augmentation" from end of each Augmentation

### ISSUE THREAD

**Issue by jboarman** [sparkfish/augraphy#48]
Looking at Albumentations as a guide, compositions should be streamlined to remove duplicate "Augmentation" naming from the end of each augmentation class added to a composition, for example:

```
A.Compose([
        A.HorizontalFlip(p=0.5),
        A.ShiftScaleRotate(p=0.5),
        A.RandomBrightnessContrast(p=0.3),
        A.RGBShift(r_shift_limit=30, g_shift_limit=30, b_shift_limit=30, p=0.3),
    ])
```

Also, it would be nice if a list was automatically mapped to an `AugmentationSequence`.

**Comment by proofconstruction** [comment]
Removed the trailing "Augmentation" from class names with [this commit](https://github.com/sparkfish/augraphy/commit/028ab44ef10d9191561b67b8b2d31ab2ac104ce2)

**Comment by proofconstruction** [comment]
Allowed pipeline phases to be bare lists [here](https://github.com/sparkfish/augraphy/commit/bc1513fb75bc2a8f22de356e4e7ef134d2b69618)
