### ISSUE TITLE
Error in DirtyRollersAugmentation

### ISSUE THREAD

**Issue by kwcckw** [sparkfish/augraphy#5]
Hi,

Facing error with :

        post_phase = AugmentationSequence([
                
            DirtyRollersAugmentation(
                line_width_range=(8, 12),
                probability=1),
                
            LightingGradientAugmentation(),
            BrightnessAugmentation('post'),
            SubtleNoiseAugmentation(),
            JpegAugmentation()
        ])

Error:

        File "C:\augraphy\augraphy-dev\src\Augraphy\Augmentations.py", line 236, in __call__
            if (not self.debug and rotate):
        
        AttributeError: 'DirtyRollersAugmentation' object has no attribute 'debug
        
        
        
There wasn't any "self.debug" so the "self.debug" should be removed?

![image](https://user-images.githubusercontent.com/52521979/124248812-cd6b5a80-db55-11eb-9c65-d02a96bb20dc.png)

Same as "self.transform":

      File "C:\augraphy\augraphy-dev\src\Augraphy\Augmentations.py", line 240, in __call__
        mask = self.transform(self.create_scanline_mask, image.shape[1], image.shape[0], line_width)
      
      AttributeError: 'DirtyRollersAugmentation' object has no attribute 'transform'
      
      
Or DirtyRollersAugmentation is still under development?

**Comment by tbrettallen** [comment]
This was a property that has been removed. I've updated the code to correct this and deployed the fix in 2.0.5

Thanks for pointing this out!
