### ISSUE TITLE
Folding Augmentation Layer

### ISSUE THREAD

**Issue by proofconstruction** [sparkfish/augraphy#52]
@kwcckw a question about the Folding augmentation:

Currently the Folding augmentation applies to the ink layer, but the fold effect happens to already-printed paper, so shouldn't it go in the post layer?

**Comment by kwcckw** [comment]
Yes, thanks, so it should be at the end of paper phase or early post phase, which one do you think is better?

**Comment by proofconstruction** [comment]
I think it makes the most sense for the "physical" augmentations to go in the post phase.

The JPEG augmentation should probably be applied before the paper fold, so artifacts from the JPEG compression appear folded as well. I think _late_ in the post phase would be best for things like this.

**Comment by kwcckw** [comment]
Okay, then I guess it should be the last argumentation at the post phase augmentation sequence. Let me test it a bit to see the result and i will update it again. Thanks for the suggestion.

**Comment by proofconstruction** [comment]
Merged PR #50 solving this.
