### ISSUE TITLE
Add handwritten `Scribbles` in pen, pencil or marker

### ISSUE THREAD

**Issue by jboarman** [sparkfish/augraphy#53]
It could be useful to reproduce random scratches, artifacts or annotations created using a pen or pencil.  Below are sample references for lines created using handwriting instruments.

### Sample References

![image](https://user-images.githubusercontent.com/1108065/129800884-0c2c4d68-ab3a-41f0-9e9e-13e285acb985.png)
![image](https://user-images.githubusercontent.com/1108065/129800903-7809eedc-d292-4d4c-8f65-d571a1adbd28.png)
![image](https://user-images.githubusercontent.com/1108065/129801142-dddf5539-3856-4267-ad48-0ab6cb718823.png)

**Comment by tbrettallen** [comment]
Added PencileScribbles augmentation (see d496cef9c9c718252ade273f7d8508bcf34e7882). With default settings it will produce something like this.
![lazy_scribbled_out](https://user-images.githubusercontent.com/3762313/129956275-d699c69c-6778-4fe6-bd79-85a0ca66e03f.png)

With size_range set large enough like this
``` PencilScribbles(size_range=(2000, 2020), p=1.0)```
It can produce images like this.
![PencilScribbles](https://user-images.githubusercontent.com/3762313/129957003-219363d1-941e-400b-aa68-13e5a530369d.png)


With brightness_change set to 32 instead of the default 128
``` PencilScribbles(brightness_change=32, size_range=(2000, 2020), p=1.0)```
It can create charcoal-like strokes instead of graphite-like strokes as seen belo
![CharcoalScribbles](https://user-images.githubusercontent.com/3762313/129956716-0341a0d1-f646-4784-8eba-56e61a4cfe5a.png)

**Comment by jboarman** [comment]
Looks really great @tbrettallen!  🥇 

To a future dev looking at this issue, we could potentially expand this by applying this effect to _lorem ipsum_ text that is generated using cursive fonts built in to OpenCV:

```
FONT_HERSHEY_SCRIPT_COMPLEX
FONT_HERSHEY_SCRIPT_SIMPLEX

```
![image](https://user-images.githubusercontent.com/1108065/129962039-54411bc0-b4f3-48c1-8849-a99a6c60fad5.png)

Another source of handwriting text could come from the [IAM Handwriting Database](https://fki.tic.heia-fr.ch/databases/iam-handwriting-database) which includes handwriting samples from 657 writers, 1,539 pages of scanned text, 5,685 isolated and labeled sentences and 13,353 isolated and labeled text lines.

![image](https://user-images.githubusercontent.com/1108065/130465156-018b5376-1241-4a1d-8f68-b2c8b2f3b636.png)

**Comment by jboarman** [comment]
@shaheryar1 @kwcckw Would either of you be interested in adding documentation for this effect?

Also, I'm wondering if we should create notebooks for each feature.  That's something we can discuss further in #33, but we could use this example as a starting point for testing out that concept.  (Note that @proofconstruction has revised the documentation structure to help make it a bit more manageable.)

**Comment by kwcckw** [comment]
> 
> 
> @shaheryar1 @kwcckw Would either of you be interested in adding documentation for this effect?
> 

By creating documentation, do you mean adding notebook on this particular augmentation? Since right now i don't see any related page on the documentation except the one in the Readme.

> Also, I'm wondering if we should create notebooks for each feature. That's something we can discuss further in #33, but we could use this example as a starting point for testing out that concept. (Note that @proofconstruction has revised the documentation structure to help make it a bit more manageable.)

I think we should create notebook with specific use case by using this augmentation? It should be a pipeline consists of this augmentation , and the other augmentations too. Otherwise, it might be not so relevant to create 1 notebook for each augmentation, some are not quite distinct on their own.

**Comment by jboarman** [comment]
> By creating documentation, do you mean adding notebook on this particular augmentation? 

@kwcckw Sort of.  The README was just updated with all the documentation moved around into a more organized format.  Check out the new `doc` folder.

> … should be a pipeline consisting of this augmentation , **and** the other augmentations too.  Otherwise, it might be not so relevant to create 1 notebook for each augmentation, some are not quite distinct on their own.

Valid point.  Some augmentations won’t stand on their own.  However, I think (eventually) we should strive to create notebooks documentation that is very narrowly defined so that the effect of an augmentation is center stage in the documentation of that augmentation, where possible.  This _pencil scribbles_ augmentation, for example, stands alone very well and would be obfuscated in a sample notebook that engaged other augmentations.

Perhaps a compromise is some hybrid of shared notebook samples for augmentations that go well together, which will result in fewer notebooks that we would have to maintain within the repo.

**Comment by kwcckw** [comment]
> 
> 

> @kwcckw Sort of. The README was just updated with all the documentation moved around into a more organized format. Check out the new `doc` folder.
> 

I see, sorry i didn't aware of that previously. Yea, i will include the documentation after i go through the code on the new agumentation.

> 
> Valid point. Some augmentations won’t stand on their own. However, I think (eventually) we should strive to create notebooks documentation that is very narrowly defined so that the effect of an augmentation is center stage in the documentation of that augmentation, where possible. This _pencil scribbles_ augmentation, for example, stands alone very well and would be obfuscated in a sample notebook that engaged other augmentations.
> 
> Perhaps a compromise is some hybrid of shared notebook samples for augmentations that go well together, which will result in fewer notebooks that we would have to maintain within the repo.

Okay, then i think we need to create a standardize notebook format for all augmentation and create each of them first. Once we are having a clear visualization on each augmentation, then we can decide whether to merge them or not.

**Comment by shaheryar1** [comment]
I was having the same confusions about making seperate notebooks for each augmentation. @kwcckw  Once you write a create a standard format, do share it with me. As there are plenty of augmentations to consider , we can divide the task.

**Comment by kwcckw** [comment]
> 
> 
> I was having the same confusions about making seperate notebooks for each augmentation. @kwcckw Once you write a create a standard format, do share it with me. As there are plenty of augmentations to consider , we can divide the task.

Right now here are the 2 main notebooks example from my end:
1. https://colab.research.google.com/drive/1hLHyyvNi-cRRDOcqtPnZPCw4j25oZMDG?usp=sharing
2. https://colab.research.google.com/drive/1MXNhPQ_37aiPmAOkfKNCDhKnlaPc1zDt?usp=sharing

I'm following the steps of:

1. Install Augraphy
2. Download sample image using gdown
3. Initialize libraries
4. Initialize pipeline
5. Apply pipeline to image

Is this good enough or do you have any suggestion to improve the workflow in the notebook?

**Comment by proofconstruction** [comment]
Added a template colab notebook, linked in #56

**Comment by jboarman** [comment]
The pencil-oriented implementation in `PencilScribbles` is well implemented ([see code](https://github.com/sparkfish/augraphy/blob/08954c29fd90921cddf24a36298039bcba5b477d/augraphy/augmentations/pencilscribbles.py#L10-L48)) which uses noise and grey color to emulate a pencil stroke.

However, we still lack the ability to produce ink-like lines in various colors, as originally intended, which would contain less noise than a pencil stroke and have more diverse range of stroke widths (e.g. thinner pen ink vs thicker markers).

We should generalize this to simply `Scribbles` with stroke parameters that can be randomized.

Stroke parameters would include:

* `stroke_color` - random defaults would be typical colors such as black, grey, blue, red
* `stroke_width` - default ranges typical for ink, pen or marker
* `stroke_noise` - less noise would be more like a dark marker or pen, while more would be a pencil or possibly a marker)
* `stroke_type` - _defaults_ above stroke parameters to values suitable for implementing a `pen`, `pencil` and `marker`; overrides would be honors while setting default param values where not explicitly set

**Comment by kwcckw** [comment]
This should be resolved with the update in this pull request:
https://github.com/sparkfish/augraphy/pull/282
