### ISSUE TITLE
Feature Request for adding OpticalDistortion in Post Phase.

### ISSUE THREAD

**Issue by shaheryar1** [sparkfish/augraphy#6]
Optical distortion is kind of a lens error that can occur when an image is taken from camera. By adding this augmentation this library can also support camera captured images effects.
Below is a sample image with optical distortion added to it

![image](https://user-images.githubusercontent.com/43179913/124565588-a06fbe00-de5b-11eb-81e8-35f54cb9212a.png)

**Comment by kwcckw** [comment]
Usually we need lens intrinsic parameters to solve the those error accurately. So at this point , do you have any library in mind that help be helpful in this case?

**Comment by jboarman** [comment]
@shaheryar1  I don't want to diminish any suggestions or ideas, but I think we should distinguish the goals of this project from other image augmentation libraries.  For Augraphy, the intent is to focus on creating synthetic documents that appear to be scanned or faxed (or captured from a camera) for various AI/ML tasks that depend on realistic datasets.

I know you mentioned this is an issue introduced from lens error, so I assume it could potentially translate to scanning a document from a camera phone.  If so, can you provide an example that applies to a document type source that we are trying to reproduce?

**Comment by jboarman** [comment]
@shaheryar1 I think we can close out this issue since we can address this more broadly with the separate issue (#25) being created for supporting Albumentations and Imgaug transformations.

**Comment by shaheryar1** [comment]
Yeah sure.
