### ISSUE TITLE
Add "Leaky Ink" Effect Augmentation

### ISSUE THREAD

**Issue by kwcckw** [sparkfish/augraphy#61]
I came across several images with effect looks like ink is leaking into the paper, and usually the effect is at the borders or edges of paper. Probably we can add this effect too?

Example:
![img_301](https://user-images.githubusercontent.com/52521979/130756654-234ed89a-53a7-4ff6-b3d7-82a4121d81e0.png)
![img_137174](https://user-images.githubusercontent.com/52521979/130756669-92a018ae-abe5-4fad-8ca4-4e239357949a.png)

 A more severe ink leaking example:
![img_136996](https://user-images.githubusercontent.com/52521979/130756790-4145fa74-156e-49d5-b8ad-32928d95ebd4.png)

Please suggest a better name for this augmentation too.

**Comment by proofconstruction** [comment]
This effect appears all the time, especially in scans of faxes of old documents.

I think this can probably be a part of BadPhotoCopy, but we can start by developing it separately. For now, we could use BadFax for the name, to fit BadPhotoCopy.

In all of these images, we can see a white border around the text inside the large dark regions. We can probably do something like the following to replicate this effect:
1. randomly select a region to add this effect to,
2. use the Sobel filter to get edges in this region (A),
3. add noise around the edges in this region to "enlarge" the edge mask (B),
4. subtract the edge mask from the region, removing the text
5. apply very heavy noise in the region
6. add the negative of (B) back to the region, creating a white area around the text,
7. add (A) back to the image, printing black text over the white region from part 6

**Comment by kwcckw** [comment]
Right, this should be feasible with current badphotocopy augmentation. Probably we just need to adjust the code a bit to produce a different noise pattern.

**Comment by proofconstruction** [comment]
Can we produce a copy of this with BadPhotoCopy and/or the upcoming Faxify?

**Comment by kwcckw** [comment]
> 
> 
> Can we produce a copy of this with BadPhotoCopy and/or the upcoming Faxify?

Not with Faxify, but it is possible with Badphotocopy, I will work on a different hash type in BadPhotoCopy to produce this effect after my next update on the Faxify.

**Comment by proofconstruction** [comment]
Does the new Faxify update allow this kind of effect?

**Comment by kwcckw** [comment]
> 
> 
> Does the new Faxify update allow this kind of effect?

Nope, faxify is creating something like monochrome (black & white) and halftone. We have something similar but not exactly with badphotocopy (hash type = 1). For example:

![image](https://user-images.githubusercontent.com/52521979/134806907-2f556977-11a2-4ba6-b5ec-b64826dbd9a9.png)

We are still not able to create a consistent wavy pattern yet, so is this really needed? If yes i will look further on how to reproduce it.

**Comment by proofconstruction** [comment]
I think we could use the following algorithm to reproduce this effect with the wave pattern:

1. randomly choose 2 edges of the page (must be different edges), `edge1` and `edge2`
2. randomly choose a point on each of the edges, let's call them `p_start` and `p_end`
3. randomly pick a number `n`, maybe in the interval (3,7) to start
4. randomly pick `n` points in the image, `p1`, `p2`, ..., `pn`
5. use the Chaikin algorithm to create a contour connecting `p_start`, `p1`, ..., `pn`, `p_end`
6. randomly pick one side of this contour
7. use the contour, `edge1`, and `edge2` as the boundary of a region of the page
8. get the mask corresponding to this region, with all transparent pixels in the other part of the mask
9. apply `BadPhotoCopy` to this mask
10. layer the mask back onto the original document

**Comment by kwcckw** [comment]
Good idea, i think we can try this out.

**Comment by kwcckw** [comment]
> 
> 
> Good idea, i think we can try this out.

I tried but looks like i'm getting a straight line with `chaikin` and `smooth`, is there any example of `chaikin` usage? Anyway, right now i'm trying to use a sine wave curve to reproduce a similar effect, i will push again when it is done.

**Comment by jboarman** [comment]
> ...looks like i'm getting a straight line with `chaikin` and `smooth`, is there any example of `chaikin` usage?

The [Strikethrough](https://github.com/sparkfish/augraphy/blob/4db0a0d49654d241d6705490fee96553c679830b/augraphy/augmentations/strikethrough.py#L97) augmentation uses chaikin via the call to smooth.

This may be oversimplifying it, but I think the idea is first to create a sequence of random points across the page in such a way that they could be connected and smoothed.  The smoothed line would connect any one side of the page to any of the 4 sides (including the starting side).

Then, complete the creation of an enclosing shape using from 1 to 5 straight lines, depending on which direction was chosen and the location of the start/stop points.  The straight lines will either join to a corner or the start/stop points.

The enclosing shape would then serve as the mask for partially applying the bad copy effect.

![image](https://user-images.githubusercontent.com/1108065/135767345-9a00e671-2eff-4b04-b09c-e5cf09200d57.png)

**Comment by proofconstruction** [comment]
^ This is exactly what I meant

**Comment by kwcckw** [comment]
I tried with this approach, the output looks jagged, it wouldn't look natural in way:

The code to reproduce it:
        
        img = np.zeros((800,800),dtype='uint8')
        
        point_x = [0, 100, 200, 250, 450, 500]
        point_y = [100, 450, 50, 300, 50, 300]
        
        for i in (range(len(point_x)-1)):
            
            point1 = [point_x[i], point_y[i]]
            point2 = [point_x[i+1], point_y[i+1]]
            points = chaikin([point1,point2])
            smooth_points = smooth(points,5) 
            for x,y in smooth_points:  
                img[int(y),int(x)] = 255
        
        plt.figure()
        plt.scatter(point_x, point_y)
        plt.imshow(img)
    
    
The output:
![image](https://user-images.githubusercontent.com/52521979/135828989-ec144738-ef56-4ef3-a253-661443d9c14a.png)

To smooth it, i tried with some curve fitting:

The code to reproduce it:

        img = np.zeros((800,800),dtype='uint8')
        ysize, xsize = img.shape[:2]
        
        point_x = [0, 100, 200, 250, 450, 500]
        point_y = [100, 450, 50, 300, 50, 300]
        
        for i in (range(len(point_x)-3)):
            
            all_x = [point_x[i], point_x[i+1], point_x[i+2], point_x[i+3]]
            all_y = [point_y[i], point_y[i+1], point_y[i+2], point_y[i+3]]
            xnew = np.linspace(min(all_x), max(all_x), 500).astype('int')
            tck = splrep(all_x, all_y)
            ynew = splev(xnew, tck)
            
            for x,y in zip(xnew, ynew):   
                img[min(int(y),ysize-1),min(int(x),xsize-1)] = 255
        
        plt.figure()
        plt.scatter(point_x, point_y)
        plt.imshow(img)


The output:
![image](https://user-images.githubusercontent.com/52521979/135829068-0997314b-dff2-4b3a-a0bd-0dfbcf7e1f2d.png)

We can further mask the overlapped area:
![image](https://user-images.githubusercontent.com/52521979/135829136-b53e5f2b-5eca-4a8c-80bd-9eb104f01916.png)

So i think we need an additional curve fitting process to create a more natural effect.

**Comment by shaheryar1** [comment]
Ok, so there is a logical error here while applying the chaikins algorithm. By writing the smooth function inside the `for i in (range(len(point_x)-3)):` you are basically smoothing each pair of points independently (which is a line). However, the algorithm needs a list of more than 2 points to generate a smoothing effect.

Correct way would be
```
   img = np.zeros((800, 800), dtype='uint8')

    point_x = [0, 100, 200, 250, 450, 500]
    point_y = [100, 450, 50, 300, 50, 300]
    points=[]
    for i in (range(len(point_x) )):
        p = [point_x[i], point_y[i]]
        points.append(p)
    print(points)
    smooth_points = smooth(points, 10)
    for x, y in smooth_points:
        img[int(y), int(x)] = 255

    plt.figure()
    # plt.scatter(point_x, point_y)
    plt.imshow(img,cmap="gray")
    plt.show()
```
![Figure_1](https://user-images.githubusercontent.com/43179913/135900318-e80001b4-4f20-458e-97c9-b1b1ea7cc87f.png)

**Comment by kwcckw** [comment]
> 
> 
> Ok, so there is a logical error here while applying the chaikins algorithm. By writing the smooth function inside the `for i in (range(len(point_x)-3)):` you are basically smoothing each pair of points independently (which is a line). However, the algorithm needs a list of more than 2 points to generate a smoothing effect.
> 

Ah, thanks, this should be suitable to generate the wave pattern and replace the current curve fitting workflow in `Badphotocopy`. We may either mask the top or bottom part of wave too:

![image](https://user-images.githubusercontent.com/52521979/135943912-5cb1466c-5879-468a-b4a7-d427b212fe7d.png)


Also it would be nice if we can at least include some comments or notes in those functions, so that the other user know the correct way to use it too.

**Comment by proofconstruction** [comment]
This looks great, but I think we still want the curve to end at one of the edges so it looks more natural.

I also agree that we always need more comments, and we should have a markdown file in the `docs` folder for every augmentation.

**Comment by shaheryar1** [comment]
> Also it would be nice if we can at least include some comments or notes in those functions, so that the other user know the correct way to use it too.

Sure, I will do this in my next PR.

**Comment by proofconstruction** [comment]
These can now be reproduced with BadPhotoCopy, right?

**Comment by kwcckw** [comment]
> These can now be reproduced with BadPhotoCopy, right?

Not exactly, we can reproduce a similar effect, but those noise look sparser (lighter). I will include another update to adjust the noise density later.

**Comment by jboarman** [comment]
@kwcckw I believe we have reproduced this effect in one of the archetypes; however, I don't know that we have generalized the generation of this effect in a parameterized and natural way within the library.  Can you confirm the current state of this feature implementation?

**Comment by kwcckw** [comment]
> @kwcckw I believe we have reproduced this effect in one of the archetypes; however, I don't know that we have generalized the generation of this effect in a parameterized and natural way within the library. Can you confirm the current state of this feature implementation?

This is now in` BadPhotoCopy`,  by enabling `wave_pattern`, we should see this effect.

![image](https://user-images.githubusercontent.com/52521979/224517530-61ee3ece-f376-48e4-a185-4328ced23ab2.png)
