### ISSUE TITLE
Create `Faxify` Augmentation

### ISSUE THREAD

**Issue by jboarman** [sparkfish/augraphy#68]
Here are the effects that a faxed document experiences:

* Downsamples image to 200 DPI (presumably this happens first, though the order could be a random decision point within the augmentation)
* Binarizes to black/white colors, applying thresholding, randomly using one of: half-toning, ADAPTIVE_THRESH_MEAN_C, ADAPTIVE_THRESH_GAUSSIAN_C, THRESH_BINARY (v=127), or THRESH_OTSU

The resolution should be assumed to have already been normalized (to 300 DPI) in advance of calling this augmentation, OR the source resolution could be provided as a parameter so that proper scaling can be calcutated to a convert to 200 DPI. Will may need to re-scale it back to the source resolution (after being downsampled) so that other augmentations, that rely on a normalized resolution, can be applied after this augmentation has been applied.

Phaxio has a short and simple article showing the difference in [thresholded ("monochrome") vs halftoned faxes](https://www.phaxio.com/blog/guide/monochrome-vs-halftone).

Thresholding basics are covered in this [OpenCV Tutorial](https://www.docs.opencv.org/master/d7/d4d/tutorial_py_thresholding.html).

![image](https://user-images.githubusercontent.com/1108065/131511712-0514e78c-47c9-4077-83bc-a697560a47ca.png)

### Example PDFs (from Phaxio):
[original.pdf](https://github.com/sparkfish/augraphy/files/7084040/Original.pdf)
[monochrome.pdf](https://github.com/sparkfish/augraphy/files/7084042/monochrome.pdf)
[halftone.pdf](https://github.com/sparkfish/augraphy/files/7084039/halftone.pdf)

**Comment by kwcckw** [comment]
I tested several implementations of halftone and i think this is the best and closest to the example above:

![image](https://user-images.githubusercontent.com/52521979/131819880-fd0d7925-8750-413b-96b9-8cac8663cf9e.png)

![image](https://user-images.githubusercontent.com/52521979/131821481-80177423-dd2c-4b18-a9ca-d038d275ef35.png)

Example of the other implementation:

![image](https://user-images.githubusercontent.com/52521979/131823284-5265638f-2156-453b-956e-a7aa31e66a43.png)

![image](https://user-images.githubusercontent.com/52521979/131823472-82009f4c-b8f0-4f0d-80df-577b749c7a9a.png)


What do you guys think?

**Comment by jboarman** [comment]
@kwcckw I concur with your assessment.  Your suggestion looks good. 

I’m assuming the Phaxio implementation is tweaked for the low resolution of a fax machine, which is why their output differs.

It seems to favor a straight monochrome effect, instead of halftone, for near black values.  You should be able to emulate that effect by forcing the pixels to true black that are within some threshold prior to halftoning the image.

If the halftone effect messes with true black, then you will have to separate pixels that are near black into a separate matrix and overlay them on top of the halftone output.

**Comment by kwcckw** [comment]
> It seems to favor a straight monochrome effect, instead of halftone, for near black values. You should be able to emulate that effect by forcing the pixels to true black that are within some threshold prior to halftoning the image.
> 

Right, but the question would be are we gonna do that in our augmentation too? Although it looks better in that way.

> If the halftone effect messes with true black, then you will have to separate pixels that are near black into a separate matrix and overlay them on top of the halftone output.

Yes, i will try that and check again whether it is better, thanks.

**Comment by proofconstruction** [comment]
We'll probably need it in more places, so I put a `binaryThreshold` function in `augmentations/lib.py` that takes an image and a cv2.THRESH_ value (defaults to Otsu), makes the image grayscale, then applies the threshold.

(I also forgot to `pre-commit install` in my new development container, so I originally pushed a non-PEP8-compliant commit. See how important it is to have pre-commit hooks? :grin: )

**Comment by kwcckw** [comment]
> 
> 
> We'll probably need it in more places, so I put a `binaryThreshold` function in `augmentations/lib.py` that takes an image and a cv2.THRESH_ value (defaults to Otsu), makes the image grayscale, then applies the threshold.
> 

Okay, we would need several thresholding methods so i gonna edit that section again if needed.

**Comment by proofconstruction** [comment]
Completed with PR #87

**Comment by jboarman** [comment]
Real faxed example with lots of dithering
![image](https://user-images.githubusercontent.com/1108065/167941658-b8c9c4cc-448c-4c76-88c8-a40930484523.png)
