### ISSUE TITLE
Feature Request for adding an Interactive web demo

### ISSUE THREAD

**Issue by shaheryar1** [sparkfish/augraphy#7]
To show the capabilities this repo should add an interactive web-demo where the end-user can apply any type of augmentation, adjusts the parameters , to see the results of any augmentation Sequence in real time.

**Comment by kwcckw** [comment]
Or it actually could be a GUI (web or non web based), with adjusting slider, button and etc to enable user adjust and see the results in real time.

**Comment by jboarman** [comment]
I really like this idea.  I'll suggest that it will be more intensive to create this demo than other work we prioritize.  But, this would be great way to show off the functionality of the library once we can make this a priority.

To expand on the concept for when we are ready, this ideas would involve setting up a demo built and deployed using _GitHub Actions_ to publish a simple Flask (or FastAPI) app to Vercel or Azure Web App.  So, it would have both a backend service aspect as well as a front-end UI.

**Comment by proofconstruction** [comment]
In either case, this might be easiest to do with a Juptyer notebook and `ipywidgets` to produce value sliders, buttons, etc.

Given the target audience, I think we might just want to make a demo that can be downloaded and run locally (a Jupyter notebook is very appropriate for this too). Anyone using Augraphy should be comfortable enough using python on their own machines, and it would eliminate extra cost and potential for abuse (e.g. flipping the slider back and forth a ton to rack up the Azure bill). A less interactive demo would address that, but with the associated cost of being less friendly.

**Comment by shaheryar1** [comment]
Great suggestion @proofconstruction . I have addressed this in issue #33 . Soon, I will be working on it. Kindly provide valuable suggestions for demo notebooks on the issue.

**Comment by jboarman** [comment]
Closed in favor of creating Notebooks.  See #33.
