### ISSUE TITLE
Audit numpy array code

### ISSUE THREAD

**Issue by proofconstruction** [sparkfish/augraphy#71]
Some of my favorite moments as a teacher come when I make mistakes in front of my students. Here's one for my colleagues:

Perhaps embarrassingly, I just learned (while making `OverlayBuilder`) that numpy arrays are accessed in row-major order, so calculations involving image height happen in the **first** entry of the array access, meaning that `expression1` in `array[expression1, expression2]` will affect the **y-component** of the index position. In the process of writing that class, I ran into a bug where, when I tried to draw binder holes on the *left* side of the image, the output had binder holes along the *top*, transposed from my intent.

This is undoubtedly old news to everyone else who will ever read this, but I want to raise it here anyway; any code I've ever touched that contains numpy arrays should be checked to make sure any relevant computations are actually occurring in the correct position.

I miss Fortran.

**Comment by kwcckw** [comment]
Yea, so most of the time we will need to go through doc of those functions. Typically, opencv is having x-component first, while numpy is having y-component first , and it's kinda confusing when you are having mixing of numpy and opencv functions.

**Comment by proofconstruction** [comment]
All `cv2` calls use the correct order of array/dimension arguments

**Comment by kwcckw** [comment]
> 
> 
> All `cv2` calls use the correct order of array/dimension arguments

Yea, so far i didn't see any incorrect order of x and y yet.
