### ISSUE TITLE
Question on the LICENSE

### ISSUE THREAD

**Issue by kwcckw** [sparkfish/augraphy#72]
I intend to use a section of code from other repo which is under Apache License 2.0:

![image](https://user-images.githubusercontent.com/52521979/132468735-95a770d3-c238-4501-87c1-bfa2f18a73fe.png)

Since the license term is not same with our repo, is it advisable to use them? Or we should avoid that if possible?  I can rewrite most of the code, but it will be taking more time instead.

**Comment by proofconstruction** [comment]
Which code, and from which repo?

The answer is, "it depends". We want to avoid adding other dependencies than the big ones (numpy, cv2, etc.), but for certain things we might have a good reason to.

**Comment by jboarman** [comment]
To add to this conversation, this definitely requires a case-by-case decision to be made.

I think it’s safe, in this case, to include a copy of a class or source file from an Apache 2.0 project as long as the source code includes a proper preamble documenting its source and its applicable license.  We can wrap that snippet or embed in our files as needed, as long as it’s really clear where their code begins/ends.

Licenses can get sticky, but at least for Apache 2.0 licenses we are explicitly allowed to include their code in our project and release under a different license.

**Comment by kwcckw** [comment]
I see, thanks for the information. I'm already rewrite the code so i guess it would be still better to not use the code unless it is really not reproducible since we can avoid any unnecessary troubles.
