### ISSUE TITLE
Failed Test case

### ISSUE THREAD

**Issue by shaheryar1** [sparkfish/augraphy#73]
I am trying to create a PR for #63, but facing this error in the test cases. Can someone guide me on how to resolve this?
![image](https://user-images.githubusercontent.com/43179913/132494411-0742abdb-6418-4cf7-b82b-a8a505f24531.png)

**Comment by proofconstruction** [comment]
Sure - I've recently added these CI tests, which are documented a bit [here](https://github.com/sparkfish/augraphy/blob/dev/doc/contributing.md)

If you scroll up in the error log a bit, you'll see this:

```shell
Reorder python imports...................................................Failed
- hook id: reorder-python-imports
- exit code: 1
- files were modified by this hook

Reordering imports in augraphy/augmentations/__init__.py
Reordering imports in augraphy/augmentations/strikethrough.py

Add trailing commas......................................................Failed
- hook id: add-trailing-comma
- exit code: 1
- files were modified by this hook

Rewriting augraphy/utilities/figsharedownloader.py
Rewriting augraphy/augmentations/strikethrough.py

black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted augraphy/augmentations/dirtydrum.py
reformatted augraphy/augmentations/badphotocopy.py
reformatted augraphy/augmentations/lib.py
reformatted augraphy/augmentations/folding.py
reformatted augraphy/augmentations/lowinkline.py
reformatted augraphy/augmentations/pencilscribbles.py
reformatted augraphy/augmentations/strikethrough.py
reformatted augraphy/base/paperfactory.py
reformatted augraphy/utilities/figsharedownloader.py
reformatted augraphy/utilities/imageoverlay.py
reformatted augraphy/utilities/overlaybuilder.py
All done! ✨ 🍰 ✨
11 files reformatted, 35 files left unchanged.
```

What this means is, the code checkers we run in GitHub Actions thought there were incorrect parts of those files, so they changed them to the correct format. These tools can't automatically fix the files you commit or push, but if you use `pre-commit` (documented in https://github.com/sparkfish/augraphy/blob/dev/doc/contributing.md) locally, they can fix those files, *prevent you from committing incorrectly-formatted code*, and then when you commit again, the files you commit will be correctly formatted.

Try installing `pre-commit` with `pip install pre-commit`, and then in your project directory run `pre-commit run --all-files` to make the code checkers reformat everything.

Let me know if you need more help

**Comment by proofconstruction** [comment]
Looks like you got it
