### ISSUE TITLE
Reproducing Archetypes

### ISSUE THREAD

**Issue by proofconstruction** [sparkfish/augraphy#74]
I spent an uncomfortable amount of time staring at the selected archetypes (in the Google Drive folder everyone reading this should have access to), and wrote some notes about each of them.

These notes are at the top of Colab notebooks in that same Google Drive folder, where we can work on the associated images.

**Comment by proofconstruction** [comment]
I've added a small block to `gdown` and display the image, so we have it available for reference while building these pipelines.

All of the archetypes now have separate issues, linked above. We should discuss reproduction of each specific archetype in its own issue, and any discussion of the general project should occur in this issue.

**Comment by proofconstruction** [comment]
Most of the original documents have some very sparse noise in the form of small black spots, only a few across the whole page. In my notes for each of these I said we might use BadPhotoCopy with a very low `noise_density` to achieve this effect, but I don't think this will work.

Which augmentation should we use to randomly introduce just a few small dots?

**Comment by kwcckw** [comment]
> 
> 
> Most of the original documents have some very sparse noise in the form of small black spots, only a few across the whole page. In my notes for each of these I said we might use BadPhotoCopy with a very low `noise_density` to achieve this effect, but I don't think this will work.
> 
> Which augmentation should we use to randomly introduce just a few small dots?

At this point, I think it would be still `BadPhotoCopy`, I'm still exploring on those additional hash types to generate different kind of noise effect, I will compile a list of possible effect with `BadPhotoCopy` later.

**Comment by kwcckw** [comment]
> 
> 
> Most of the original documents have some very sparse noise in the form of small black spots, only a few across the whole page. In my notes for each of these I said we might use BadPhotoCopy with a very low `noise_density` to achieve this effect, but I don't think this will work.
> 
> Which augmentation should we use to randomly introduce just a few small dots?

I created some variant of noises, and to clarify, is any of example below match the one you mentioned?

Example1:
![image](https://user-images.githubusercontent.com/52521979/132988098-b9ee546b-6ad2-4793-866c-ff4fb7dd9562.png)

Example2:
![image](https://user-images.githubusercontent.com/52521979/132988140-76649f99-bc68-423d-8393-6d21ade20e76.png)

Example3:
![image](https://user-images.githubusercontent.com/52521979/132988161-ca83b946-0520-4946-93b0-4a1b3d6581fb.png)


Or is it something similar to lighter version of salt and pepper noise?

**Comment by proofconstruction** [comment]
These are close, but we need even less noise. This will be good for a few of the documents, but most of them only have a few (less than maybe 10) dots

**Comment by kwcckw** [comment]
> 
> 
> These are close, but we need even less noise. This will be good for a few of the documents, but most of them only have a few (less than maybe 10) dots

I updated the hash types and it should be hash type 4 to reproduce this effect, so i guess that's the best I can do now and please check again here: https://github.com/sparkfish/augraphy/pull/88

**Comment by proofconstruction** [comment]
Everyone should be able to edit the Colab notebooks linked in the other issues.

We need to focus on trying to reproduce these documents, so we can either have a good result to show or we can identify new augmentations/changes to existing ones if we run into problems.

**Comment by kwcckw** [comment]
@proofconstruction I just tested with `1 - Letter - Diahann Carroll - 1972.ipynb`, so there are some issues when we combine several augmentations, there are some bugs and causing the unexpected output, I will check again and let you know again.

Also right now `badphotography` is setting input as `ink` layer, it should be relevant in ink layer right?

**Comment by proofconstruction** [comment]
> there are some issues when we combine several augmentations, there are some bugs and causing the unexpected output,

What are the issues and bugs?

> Also right now `badphotography` is setting input as `ink` layer, it should be relevant in ink layer right?

I think we should try to allow augmentations in any layer unless they really need to be in just one for technical reasons, so we should add `layer="post"` and `self.layer = layer` to the constructor, then change to `image = data[self.layer][-1].result` in the `__call__` method.

**Comment by kwcckw** [comment]
> 
> 
> > there are some issues when we combine several augmentations, there are some bugs and causing the unexpected output,
> 
> What are the issues and bugs?

Sorry,  from my further investigation, actually it's just due to different parameter values, now it looks fine, you may check on the output again: https://colab.research.google.com/drive/1lK85t83WAXb0dwLyZtcROzc7D-qLu9MY?usp=sharing

I think it's looking good now:
![image](https://user-images.githubusercontent.com/52521979/133888353-ddc84d0d-0bb8-4742-88b3-99372197e708.png)


> 
> > Also right now `badphotography` is setting input as `ink` layer, it should be relevant in ink layer right?
> 
> I think we should try to allow augmentations in any layer unless they really need to be in just one for technical reasons, so we should add `layer="post"` and `self.layer = layer` to the constructor, then change to `image = data[self.layer][-1].result` in the `__call__` method.

Okay, then i will add this in later for some other relevant augmentations too.

**Comment by proofconstruction** [comment]
Closed with PR #154
