### ISSUE TITLE
Feature Request for GammaAdjustment Augmentation

### ISSUE THREAD

**Issue by shaheryar1** [sparkfish/augraphy#8]
Scanners change the  gamma of the whole image most of the times. Adding this augmentation with a gamma range of 0.5 to 1.5 in the Post phase can give a variety of different augmentations. Moreover, we can also make it as "Gamma Adjustment" that will automatically detects the appropriate gamma value for each image.

**Comment by kwcckw** [comment]
>  gemma

Sorry but do you mean gamma? Gamma correction with Power Law transformation should be useful in adjusting the image intensity and hence giving a better visualization.

**Comment by shaheryar1** [comment]
Yes Gamma. Sorry for typos. I will work on my next PR to add this feature in repo

**Comment by jboarman** [comment]
I went ahead and merged this in since it looks pretty straightforward.  I'll hold off on publishing to PyPI until someone else has had a chance to test it out.

**Comment by kwcckw** [comment]
I tested it and looks fine, but one thing to take note is this augmentation is only working at post phase, and we will getting error if we put it in paper or ink phase, so it is better to add some notes and code to avoid the error if user put it at ink or paper phase. For example, adding evaluation of post data:
 
       class GammaAugmentation(Augmentation):
          def __init__(self, range=(0.5, 1.5), probability=0.5):
            super().__init__(probability=probability)
            self.range = range
        
          def __repr__(self):
            return f"GammaAugmentation(range={self.range}, probability={self.probability})"
        
          def __call__(self, data,force=False):
            if data['post']:
                img = data['post'][-1].result
                img = img.astype(np.uint8)
                value = random.uniform(self.range[0], self.range[1])
                invGamma = 1.0 / value
                table = np.array([((i / 255.0) ** invGamma) * 255
                                  for i in np.arange(0, 256)]).astype("uint8")
                print(table.shape,img.shape)
                frame= cv2.LUT(img, table)
                data['post'].append(AugmentationResult(self, frame))


Example with gamma of 0.5 amd 2:

![image](https://user-images.githubusercontent.com/52521979/124683339-648e3480-deff-11eb-874b-0c16c8f98524.png)

**Comment by shaheryar1** [comment]
Got it. I guess this issue can occur in any of the augmentation type mismatch. There should be a away to restrict this
