### ISSUE TITLE
Error in creating pull request

### ISSUE THREAD

**Issue by kwcckw** [sparkfish/augraphy#89]
I'm not sure but this is the first time I'm facing this error when creating pulling request:

![image](https://user-images.githubusercontent.com/52521979/133552684-488bff7d-38fb-4d32-88af-b9bd5e680d2f.png)

What I did earlier was merge the latest repo updates and commit the new changes:
![image](https://user-images.githubusercontent.com/52521979/133552750-34fb7af9-114d-4ef9-94f6-1c6f35cb00be.png)

@proofconstruction Do you have any idea on this problem? Else i guess i will need to detach and refork again.

**Comment by proofconstruction** [comment]
I haven't seen this before. It happens when you try to make a PR from your fork, or when you try to make a new PR from the main repository?

**Comment by kwcckw** [comment]
> 
> 
> I haven't seen this before. It happens when you try to make a PR from your fork, or when you try to make a new PR from the main repository?

Thanks, probably I'm trying to create the pull request from the main repo earlier, now I didn't get the error again.
