### ISSUE TITLE
Standardize implementation of Randomization to follow Albumentations

### ISSUE THREAD

**Issue by kwcckw** [sparkfish/augraphy#9]
### Updated Issue Description

To improve composability of pipelines and to follow current standard practices exhibited by Albumentations, we should document and update our randomness functionality:

* [x] Document support for Python's [random seed](https://github.com/albumentations-team/albumentations/issues/93) for reproducible results within transforms and pipeline composition
* [x] Document "how to" to ensure all augmentation code shares Python's random state, even if Numpy random methods are needed in internally (see [example](https://github.com/sparkfish/augraphy/blob/9e4e11ce023a6ff0cbb71003869e490cffd068be/src/augraphy/base/oneof.py#L19))
* [x] Review all library's committed code for consistency with this standard
* [x] Change to use of `p` as probability parameter for consistency with Albumentations

See Pytorch notes on [reproducibility](https://pytorch.org/docs/stable/notes/randomness.html) for ideas on what we need to document.

#### Original Issue

> I tried to generate consistent output from the image but looks like it doesn't seem to be so straight forward. So wouldn't it be better if we making those randomly initialized parameters as optional? So that we can get consistent output with the same pipeline. 
> 
> Right now i can see the problem is there are so many randomize parameters and it would be difficult to get consistent output style from a same pipeline, so if i want to use the same pipeline with multiple papers, i might end up with different inconsistent style output.

**Comment by shaheryar1** [comment]
Actually there is a way to remove randomization in the current code. To must apply an Augmentation you can set the `probability=1` or use` force=True`. Also most of the Augmentation use a `range=(lower_limit,higher_limit)` to select a value that controls the augmentation intensity. You simply can narrow down the range to get consistent results, or may be keep `lower_limit=upper_limit` .

**Comment by jboarman** [comment]
@kwcckw Are you OK with the suggestion from @shaheryar1 on minimizing the randomness on any given augmentation?  I could see some other approaches used, including the introduction of a fixed seed value, which might make for more consistent testing and reproducible results.  What do you think?

**Comment by kwcckw** [comment]
Yes, adjusting seed, probability,or use fixed range value would helps, but it wouldn't be straightforward since we need to adjust them one by one. I'm suggesting a general input argument to let user fixed the style or randomness, so that they can reproduce the same consistent output when needed.

**Comment by jboarman** [comment]
The `data` payload that is carried throughout the pipeline processing could manage the state of both a common seed value as well as centralizing a default setting for the randomness setting.  Providing an additional randomness value on a given augmentation could override the global randomness value configured for the pipeline or the value provided for a given execution of the pipeline.

**Comment by kwcckw** [comment]
> 
> 
> The `data` payload that is carried throughout the pipeline processing could manage the state of both a common seed value as well as centralizing a default setting for the randomness setting. Providing an additional randomness value on a given augmentation could override the global randomness value configured for the pipeline or the value provided for a given execution of the pipeline.

Right, we can parse the random seed via `data` to all the augmentation functions, with that we should be able to produce a reasonably consistent output.

**Comment by jboarman** [comment]
Though probably not the best practice, I updated this original issue with a specific set of actions that we should implement to address the originally-reported concern.

Additional methods for controlling randomness on a pipeline might be possible later whereby we could control randomness settings of a predefined pipeline.  But, a lot of considerations to how compositions are managed would be affected, so that functionality may be a bit out of scope for the foreseeable future.

**Comment by kwcckw** [comment]
> Additional methods for controlling randomness on a pipeline might be possible later whereby we could control randomness settings of a predefined pipeline. But, a lot of considerations to how compositions are managed would be affected, so that functionality may be a bit out of scope for the foreseeable future.

Right, so we may look into this again when we finalized composition of the code. It  might not be suitable if we add in this feature now.

**Comment by proofconstruction** [comment]
#29 resolves the first three requirements in the first post, and along with the commits [1059bf3](https://github.com/sparkfish/augraphy/commit/1059bf3cbf78d5c190cea0bf6c2b121d878147a4) and [3046819](https://github.com/sparkfish/augraphy/commit/304681901d16c78d25e65e13c498a4815963b230) (resolving the 4th) would allow us to close this issue.
