### ISSUE TITLE
Create Moiré Pattern for Screen Pic Augmentation

### ISSUE THREAD

**Issue by proofconstruction** [sparkfish/augraphy#91]
It's common to use a camera phone to take a picture of a document displayed on a computer monitor. Often this is the lowest-friction means of making a record, which doesn't involve connecting a portable storage device or sending the file with email.

It might be good to have an augmentation that replicates the visual warping effect resulting from this.
Some example shots taken from this Issue submission page, taken with my phone (and JPEG compressed to fit GitHub's upload size requirements):
![IMG_20210917_145957](https://user-images.githubusercontent.com/74747193/133745438-3e433b82-a0cc-4d92-8631-fed48fb82c43.jpg)
![IMG_20210917_150008](https://user-images.githubusercontent.com/74747193/133745447-e77186dd-c424-438e-8bc7-08c046dd5e98.jpg)

The warping effect, called [the Moiré pattern](https://en.wikipedia.org/wiki/Moir%C3%A9_pattern) is produced by interfering signals in the light produced by the screen pixel grid and the light received by the camera's sensor grid.

[This repository](https://github.com/gmelodie/silentMoire) contains code for *removing* the effect, which should be adaptable to add it back in.

**Comment by shaheryar1** [comment]
Has anyone started working on this ?

**Comment by kwcckw** [comment]
> 
> 
> Has anyone started working on this ?

Nope, i didn't work on anything related to this yet.

**Comment by proofconstruction** [comment]
I think a good start would be finding some example images of the effect and adding them to #118.

Then we can see the different patterns and decide how to reproduce them.

One relatively easy approach might be the following:
1. pick a point on the image, call it `p1`
2. pick another point on the image, call it `p2`,
3. generate some reasonable constants for a parabola with `p1` as the focus and the line connecting `p1` and `p2` as the axis,
4. generate some offset (the period of this effect)
5. draw the parabolas (or some other shape, like hyperbolas) according to the `p1` `p2` line and constants, at the offsets

I'm not sure what we should do about the pixel colors, since the shapes we draw should be close to the colors of the underlying image. Any ideas?

**Comment by shaheryar1** [comment]
I'll start working on it today by doing some initial research and experiments.

**Comment by shaheryar1** [comment]
Made some progression by overlaying linear and circular patterns and these lined patterns are produced when the camera has a high shutter rate. 

But I think we can make it better using some kind of irregular ripple effect.  

![download (2)](https://user-images.githubusercontent.com/43179913/140656374-59e1f38b-3057-4213-bef9-0731bea9fe4e.png)
![download (1)](https://user-images.githubusercontent.com/43179913/140656377-e8ef626a-0870-4f49-a509-93ccff5f7e4e.png)
![download](https://user-images.githubusercontent.com/43179913/140656573-0006623a-de1a-41bf-8898-19e9616fe7f7.png)

**Comment by kwcckw** [comment]
> Made some progression by overlaying linear and circular patterns and these lined patterns are produced when the camera has a high shutter rate.
> 
> But I think we can make it better using some kind of irregular ripple effect.
> 

Looks great, I think it will be better if we can adjust the intensity too, since it looks a little bit darker now. Also adding some gradient in the brightness will be better too .

**Comment by shaheryar1** [comment]
> Looks great, I think it will be better if we can adjust the intensity too, since it looks a little bit darker now. Also adding some gradient in the brightness will be better too .

Yes, the intensities of the patterns can be adjusted.  For the brightness gradient, I think a separate augmentation can serve the purpose here.

**Comment by shaheryar1** [comment]
Augmentation representing overlays of circular/horizontal/verticle patterns are added in this [Notebook](https://colab.research.google.com/drive/1zACc_p_xY024B7o0atIOPePKxAxGVmgB?usp=sharing). You guys can check and provide feedback

**Comment by kwcckw** [comment]
> 
> 
> Augmentation representing overlays of circular/horizontal/verticle patterns are added in this [Notebook](https://colab.research.google.com/drive/1zACc_p_xY024B7o0atIOPePKxAxGVmgB?usp=sharing). You guys can check and provide feedback

In the last section of code is there any purpose to use `create_linear_pattern` before `create_circular_pattern`?

        org_img=cv2.imread('/content/test.png')
        H,W,C = org_img.shape
        alpha=0.08
        pattern=create_linear_pattern(H,W)
        pattern=create_circular_pattern(H,W)
        
        cv2_imshow(overlay(org_img,pattern,alpha))

**Comment by shaheryar1** [comment]
This is of no significance, you can comment/remove any 1 pattern. I still have to add parameters to randomly select the pattern type and intensities.

**Comment by jboarman** [comment]
## Working Technique for an LCD Screen Pattern

This website applies a pattern overlay using CSS to get a pattern that looks a photo was taken from a screen.  There are might even be versions of generated patterns that could be applied in layers to simulate Moiré pattern.

Overlaid Version of Image:
![image](https://user-images.githubusercontent.com/1108065/158859412-a73fafb4-8f8f-44cf-a53e-90b3e091bc74.png)

Original Image:
![image](https://user-images.githubusercontent.com/1108065/158859625-7faac15e-5fbd-4d2c-8158-e1eaf13f40bd.png)

Pattern Overlay (super tiny, almost invisible image b/t brackets): [ ![screen pattern](https://user-images.githubusercontent.com/1108065/158858459-830d5349-6841-4fd2-a81f-d80b27ebb0ae.png) ]

Source URLs:
https://www.normascafe.com/locations/
https://www.normascafe.com/spillover/proto/normascafe/images/design/pattern.png
https://www.normascafe.com/spillover/proto/normascafe/images/backgrounds/deliverytruck.jpg

**Comment by jboarman** [comment]
## Moiré Effect in Displays: A Tutorial  (Lots of Maths!)
_Vladimir Saveljev, Sung-Kyu Kim, Jaisoon Kim_

> _The tutorial describes essential features of moiré patterns, as well as the circumstances, when the moiré patterns appear and how to estimate their characteristics (parameters) such as the orientation and period. The moiré effect is described in two domains, the image space (spatial domain) and in the spectral domain using the complex numbers. The tutorial covers the indicial equation method, the coplanar and noncoplanar sinusoidal gratings, the moiré effect in a spatial object (a cylinder), as well as explains the moiré wave vector, the moiré spectra, the spectral trajectories, and summarizes behavior of the visible patterns in moved/rotated gratings._
![image](https://user-images.githubusercontent.com/1108065/224506293-8483e38e-fac5-4791-ad10-7d5f9e8b3993.png)

https://www.spiedigitallibrary.org/journals/optical-engineering/volume-57/issue-03/030803/Moir%C3%A9-effect-in-displays-a-tutorial/10.1117/1.OE.57.3.030803.full?SSO=1

**Comment by kwcckw** [comment]
This is now added in https://github.com/sparkfish/augraphy/pull/413.
