### ISSUE TITLE
Choose a consistent programming style.

### ISSUE THREAD

**Issue by kwcckw** [sparkfish/augraphy#94]
So with multiple contributors, maybe we can decide and choose a consistent programming style in the repo?

For example:

1. Naming in variables:
a) Capital + lower case, for eg: `variableOne`
b) Underscore, for eg: `variable_one`

2. Comment style:
a) Same line with code, for eg:  
        `x = m + y  #x is equal to m plus y`
b) In a new line, above the code, for eg:
       `#x is equal to m plus y `
       `x = m + y  `

3. Usage of shortform in the naming of variables , functions or classes
a) Try to avoid usage of shortform, for eg, `image_rgb = cv2.imread('image.png')`
b) Use shortform whenever it is possible, for eg, `img_rgb = cv2.imread('image.png')`

Please include more possible styles, this is what i'm having in my mind now.

**Comment by proofconstruction** [comment]
This is a good idea. I'm in favor of 1.b  2.b, and 3.a. We should use the more descriptive variables when possible, and PEP8 says we should use underscores to separate different words in a variable or function name (even though I prefer mixedCase)

**Comment by kwcckw** [comment]
> 
> 
> This is a good idea. I'm in favor of 1.b 2.b, and 3.a. We should use the more descriptive variables when possible, and PEP8 says we should use underscores to separate different words in a variable or function name (even though I prefer mixedCase)

Right, the variable name should be more suggestive to their purpose, so using full term should be a better idea. In term of underscore or mixed case, actually I prefer underscore, but let's see the choice of majority. I'm not sure but can we create sort of poll here?

**Comment by proofconstruction** [comment]
We are the majority :grin:

What do you think about 1 and 2?

**Comment by kwcckw** [comment]
I would say 1b and 2b too, lets stick to this style for now.

**Comment by shaheryar1** [comment]
1. b
2. b
3. b

**Comment by proofconstruction** [comment]
So we agree on 1b and 2b.

I still think for 3, we should try to use the long form if possible. It's probably fine to use the short form in library functions (things that go in `lib.py`) though.

In general, I think it's better to see things like `image_mask_blurred` than `img_mask_blur`; the longer form isn't much more to type and carries slightly more information.

Ultimately this is a documentation thing: we're reading and understanding the code right now, but what about in 6 months? What about other people reading it and trying to get on board with the project? We want to reduce friction there if possible, and always trying to use more descriptive names is one way to help.

**Comment by kwcckw** [comment]
Well , i think for 3, as long the variable name is descriptive enough, then it should be fine, although i prefer the long name.

For example, we might not know what is `img_cnv`, so we should use something like `img_convoluted`, although `img` and `image` doesn't have much difference here.

**Comment by proofconstruction** [comment]
OK, I'm comfortable with both the long and short names (as long as we use things like `img_convoluted` instead of `img_cnv`)

As long as we agree on 1b and 2b and use these in the future, we can use good judgment about 3a/3b.
