### ISSUE TITLE
Removing Blur from Default Pipeline, Adding Blur within Augmentations

### ISSUE THREAD

**Issue by jboarman** [sparkfish/augraphy#96]
In the original pipeline, it was found necessary to blur the Ink Bleed, Dusty Ink, Low Ink Blobs and Low Ink Lines augmentations -- this blur post processing made for some very realistic output:

![image](https://user-images.githubusercontent.com/1108065/135175981-600dd807-c966-4538-84ff-3ddf5d4036c6.png)

However, in this commit (https://github.com/sparkfish/augraphy/commit/b57949a8bd97843b75333d1e7fa2b8c3176e125f), @tbrettallen started to remove that dependency on Blur.

The blur effect in this augmentation is now done directly the the effect before the noise mask is applied to the ink layer.  By directly applying the blur within the augmentation, we can retain a greater fidelity for other parts of the ink layer that do not need to be blurred.  In the event that the ink needs to be blurred throughout the image, then it can be done prior to applying other augmentations.

All augmentations in the default pipeline (or others that depend on blur processing) should be reviewed to similarly apply the blur embedded within the augmentation just as it has been done in Brett's commit referenced above.  Then, hopefully the blur can be removed from the default pipeline.

**Comment by proofconstruction** [comment]
Yes, I think we can probably move a few effects out of being stand-alone augmentations and into the shared lib. GaussianBlur for sure, and I think also SubtleNoise, Gamma, Brightness, and maybe Dithering are good candidates. Scale, too, since I can no longer remember why I thought we'd need that. (I think I wanted it as part of the approach to image overlays)

**Comment by proofconstruction** [comment]
Misunderstood above.

After auditing the augmentations code I see we already do this, and now [this commit](https://github.com/sparkfish/augraphy/commit/42d78073c1f0740659992026a9cf9c665c95509a) resolves the issue.
